{
 "title": "CI Analitics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "variant_group",
    "label": "Variant Group",
    "query": "SELECT ki.text\n       \nFROM   kind_ids ki        \nJOIN kind_type_ids AS kti\n         ON kti.id = ki.type_id\nWHERE  kti.description = 'variant_group'"
   },
   {
    "name": "variant",
    "label": "Variant",
    "query": "SELECT ki.text\nFROM   kind_ids ki \n  JOIN kind_type_ids AS kti\n    ON kti.id = ki.type_id\nWHERE  kti.description = 'variant' \n"
   },
   {
    "name": "test",
    "label": "Test",
    "query": "SELECT ki.text\nFROM   kind_ids ki \n  JOIN kind_type_ids AS kti\n    ON kti.id = ki.type_id\nWHERE  kti.description = 'test' \n"
   }
  ]
 },
 "panels": [
  { "title": "Overall CI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runs",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'overall'\n)\nSELECT\n  $__time(sr.date),\n  sr.total_runs,\n  sr.failed_runs\nFROM\n  success_ratio sr\n  JOIN kids ON sr.kind_id = kids.id\nWHERE\n  $__timeFilter(sr.date)\nORDER by\n  sr.date;"
    }
   ]
  },
  {
   "title": "Failure rato",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'overall'\n)\nSELECT\n  $__time(sr.date),\n  (sr.failed_runs/sr.total_runs::float)*100 as failure_ratio\nFROM\n  success_ratio sr\n  JOIN kids ON sr.kind_id = kids.id\nWHERE\n  $__timeFilter(sr.date)\nORDER by\n  sr.date;"
    }
   ]
  },
  {
   "title": "Pipeline duration",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'overall'\n)\nSELECT\n  $__time(et.datetime),\n  MAX(unnested_duration.duration) AS duration,\n  kids.text AS metric\nFROM\n  execution_time AS et\n  JOIN kids ON et.kind_id = kids.id\n  CROSS JOIN LATERAL UNNEST(et.duration_seconds) AS unnested_duration(duration)\nWHERE\n  $__timeFilter(et.datetime)\nGROUP BY\n  metric,\n  et.datetime\nORDER BY\n  et.datetime,\n  metric;"
    }
   ]
  },
  {
   "title": "Variant Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed runs",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'variant_group'\n    AND ki.text in ($variant_group)\n)\nSELECT\n  $__time(sr.date),\n  sr.failed_runs,\n  kids.text AS metric\nFROM\n  success_ratio sr\n  JOIN kids ON sr.kind_id = kids.id\nWHERE\n  $__timeFilter(sr.date)\nORDER by\n  sr.date;"
      }
     ]
    },
    {
     "title": "Failure rato",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'variant_group'\n    AND ki.text in ($variant_group)\n)\nSELECT\n  $__time(sr.date),\n  (sr.failed_runs / sr.total_runs :: float) * 100 as failure_ratio,\n  kids.text AS metric\nFROM\n  success_ratio sr\n  JOIN kids ON sr.kind_id = kids.id\nWHERE\n  $__timeFilter(sr.date)\norder by\n  sr.date;"
      }
     ]
    }
   ]
  },
  {
   "title": "Variants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runs",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'variant'\n    AND ki.text in ($variant)\n)\nSELECT\n  $__time(sr.date),\n  sr.failed_runs,\n  kids.text AS metric\nFROM\n  success_ratio sr\n  JOIN kids ON sr.kind_id = kids.id\nWHERE\n  $__timeFilter(sr.date)\nORDER by\n  sr.date;\n  "
      }
     ]
    },
    {
     "title": "Failure rato",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'variant'\n    AND ki.text in ($variant)\n)\nSELECT\n  $__time(sr.date),\n  (sr.failed_runs / sr.total_runs :: float) * 100 as failure_ratio,\n  kids.text AS metric\nFROM\n  success_ratio sr\n  JOIN kids ON sr.kind_id = kids.id\nWHERE\n  $__timeFilter(sr.date)\norder by\n  sr.date;\n\n"
      }
     ]
    },
    {
     "title": "Execution time",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'variant'\n)\nSELECT\n  $__time(et.datetime),\n  MAX(unnested_duration.duration) AS duration,\n  kids.text AS metric\nFROM\n  execution_time AS et\n  JOIN kids ON et.kind_id = kids.id\n  CROSS JOIN LATERAL UNNEST(et.duration_seconds) AS unnested_duration(duration)\nWHERE\n  $__timeFilter(et.datetime)\n  AND kids.text in ($variant)\nGROUP BY\n  metric,\n  et.datetime\nORDER BY\n  et.datetime,\n  metric;"
      }
     ]
    }
   ]
  },
  {
   "title": "Test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed runs",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'test'\n    AND ki.text in ($test)\n)\nSELECT\n  $__time(sr.date),\n  sr.failed_runs,\n  kids.text AS metric\nFROM\n  success_ratio sr\n  JOIN kids ON sr.kind_id = kids.id\nWHERE\n  $__timeFilter(sr.date)\nORDER by\n  sr.date;"
      }
     ]
    },
    {
     "title": "Failure rato",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'test'\n    AND ki.text in ($test)\n)\nSELECT\n  $__time(sr.date),\n  (sr.failed_runs / sr.total_runs :: float) * 100 as failure_ratio,\n  kids.text AS metric\nFROM\n  success_ratio sr\n  JOIN kids ON sr.kind_id = kids.id\nWHERE\n  $__timeFilter(sr.date)\norder by\n  sr.date;"
      }
     ]
    },
    {
     "title": "Tests execution time, > 0.1s",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "WITH kids AS (\n  SELECT\n    ki.id AS id,\n    ki.text AS text\n  FROM\n    kind_ids ki\n    JOIN kind_type_ids kti ON kti.id = ki.type_id\n  WHERE\n    kti.description = 'test'\n)\nSELECT\n  $__time(et.datetime),\n  MAX(unnested_duration.duration) AS duration,\n  kids.text AS metric\nFROM\n  execution_time AS et\n  JOIN kids ON et.kind_id = kids.id\n  CROSS JOIN LATERAL UNNEST(et.duration_seconds) AS unnested_duration(duration)\nWHERE\n  $__timeFilter(et.datetime)\n  AND unnested_duration.duration > 0.1\n  AND kids.text in ($test)\nGROUP BY\n  metric,\n  et.datetime\nORDER BY\n  et.datetime,\n  metric;"
      }
     ]
    },
    {
     "title": "Failed pipelines",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "rawSql": "WITH expanded_ids AS (\n  SELECT\n    ki.text,\n    SUM(sr.failed_runs) AS fails,\n    SUM(sr.total_runs) AS total,\n    pid\n  FROM\n    success_ratio sr\n    JOIN kind_ids ki ON ki.id = sr.kind_id\n    JOIN LATERAL unnest(sr.pipeline_ids) AS pid ON true\n  WHERE\n    ki.type_id = 4\n    AND sr.failed_runs > 0\n    AND $__timeFilter(sr.date)\n  GROUP BY\n    ki.text,\n    pid\n),\nexpanded_urls AS (\n  SELECT\n    ei.text,\n    ei.fails,\n    ei.total,\n    p.web_url\n  FROM\n    expanded_ids ei\n    JOIN pipelines p ON ei.pid = p.id\n  order by\n    ei.text,\n    p.web_url\n)\nSELECT\n  text,\n  sum(fails) as sum_fails,\n  sum(total) as sum_total,\n  ARRAY_AGG(\n    DISTINCT web_url\n    ORDER BY\n      web_url desc\n  ) AS pipeline_urls\nFROM\n  expanded_urls\nGROUP BY\n  text\nORDER BY\n  sum_fails DESC,\n  text DESC;"
      }
     ]
    }
   ]
  }
 ]
}