{
 "title": "Hosted Runners SLOs",
 "tags": [
  "hosted-runners",
  "slas",
  "service-levels"
 ],
 "time": { "from": "now-1M/M", "to": "now-1d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Hosted Runners Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runner Uptime Rate",
   "type": "stat",
   "description": "Percentage of time the runner stayed online based on successful API heartbeats.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n  (\n    gitlab_component_ops:rate_1h{type=\"hosted-runners\", component=\"api_requests\"}\n    -\n    gitlab_component_errors:rate_1h{type=\"hosted-runners\", component=\"api_requests\"}\n  )[$__range:1m]\n)\n/\nsum_over_time(\n  gitlab_component_ops:rate_1h{type=\"hosted-runners\", component=\"api_requests\"}[$__range:1m]\n)\n"
    }
   ]
  },
  {
   "title": "Availability Budget Spent",
   "type": "stat",
   "description": "Total time the runner was offline during the selected period, based on missing API heartbeat signals.",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    1 -\n    (\n      (\n        sum_over_time(sum(gitlab_component_ops:rate_1h{type=\"hosted-runners\", component=\"api_requests\"})[$__range:1m])\n        -\n        sum_over_time(sum(gitlab_component_errors:rate_1h{type=\"hosted-runners\", component=\"api_requests\"})[$__range:1m])\n      )\n      /\n      sum_over_time(sum(gitlab_component_ops:rate_1h{type=\"hosted-runners\", component=\"api_requests\"})[$__range:1m])\n    )\n  ) * ($__range_s / 3600)\n"
    }
   ]
  },
  {
   "title": "Runner Downtime",
   "type": "status-history",
   "description": "Hourly view of offline activity for the selected runner, showing when API heartbeats were missing and downtime occurred.",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "last_over_time(\n  (\n    (\n      (\n        (sum(gitlab_component_ops:rate_1h{type=\"hosted-runners\", component=\"api_requests\"}) OR on() vector(0))\n        -\n        (sum(gitlab_component_errors:rate_1h{type=\"hosted-runners\", component=\"api_requests\"}) OR on() vector(0))\n      ) > bool 0\n    )\n  )[$__range:1m]\n)\n",
     "legendFormat": "Status"
    }
   ]
  },
  { "title": "Hosted Runners Job Queuing SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Job Queue Latency",
   "type": "stat",
   "description": "Percentage of all jobs over the dashboard's range that were executed within an acceptable time. Excludes jobs that were delayed because the scaleMax threshold was hit.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\nsum(sum_over_time(\n  (\n    (\n      sum by (shard) (\n        increase(\n          (\n            sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n          )[1m:1m]\n        )\n      ) or (\n        0 * sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n      )\n    ) *\n    (\n      min_over_time(\n        (sum by(shard)(fleeting_provisioner_instances{type=\"hosted-runners\", state!=\"deleting\"}) < bool sum by(shard)(fleeting_provisioner_max_instances) * .9)[2m:1m]\n      )\n    )\n  )[$__range:1m]\n))\n /\nincrease(sum(gitlab_runner_jobs_total{type=\"hosted-runners\"})[$__range:1m])\n"
    }
   ]
  },
  {
   "title": "Jobs Violating Latency",
   "type": "stat",
   "description": "Number of jobs over the dashboard's range that exceeded the acceptable time. Excludes jobs that were delayed because the scaleMax threshold was hit.",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(\n  (\n    (\n      sum by (shard) (\n        increase(\n          (\n            sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n          )[1m:1m]\n        )\n      ) or (\n        0 * sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n      )\n    ) *\n    (\n      min_over_time(\n        (sum by(shard)(fleeting_provisioner_instances{type=\"hosted-runners\", state!=\"deleting\"}) < bool sum by(shard)(fleeting_provisioner_max_instances) * .9)[2m:1m]\n      )\n    )\n  )[$__range:1m]\n))\n"
    }
   ]
  },
  {
   "title": "Job Queuing Latency SLO Over Time",
   "type": "timeseries",
   "description": "Percentage of all jobs looking back over the dashboard's range that were executed within an acceptable time. Excludes jobs that were delayed because the scaleMax threshold was hit.",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 -\nsum(sum_over_time(\n  (\n    (\n      sum by (shard) (\n        increase(\n          (\n            sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n          )[1m:1m]\n        )\n      ) or (\n        0 * sum by (shard) (gitlab_runner_acceptable_job_queuing_duration_exceeded_total{type=\"hosted-runners\"})\n      )\n    ) *\n    (\n      min_over_time(\n        (sum by(shard)(fleeting_provisioner_instances{type=\"hosted-runners\", state!=\"deleting\"}) < bool sum by(shard)(fleeting_provisioner_max_instances) * .9)[2m:1m]\n      )\n    )\n  )[$__range:$__interval]\n))\n /\nincrease(sum(gitlab_runner_jobs_total{type=\"hosted-runners\"})[$__range:$__interval])\n",
     "legendFormat": "Job Queuing SLO"
    }
   ]
  },
  {
   "title": "Hosted Runners Successful Job Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Job Successful Rate",
   "type": "stat",
   "description": "Percentage of ci_runner_jobs over the dashboard's range that did not have internal errors.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum by(component) (\n  gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"} -  gitlab_service_errors:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n)[$__range:1m])\n/\nsum_over_time(\n  sum by(component) (\n    gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n  )[$__range:1m])\n"
    }
   ]
  },
  {
   "title": "Availability Budget Spent",
   "type": "stat",
   "description": "Estimated time over the dashboard's period where ci_runner_jobs failed due to internal errors",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum_over_time(sum by(component) (\n  gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"} -  gitlab_service_errors:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n)[$__range:1m])\n/\nsum_over_time(\n  sum by(component) (\n    gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n  )[$__range:1m])\n)) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Rolling availability",
   "type": "timeseries",
   "description": "Percentage of ci_runner_jobs over the dashboard's range that did not have internal errors, looking back over the dashboard's range window.",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(sum by(component) (\n  gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"} -  gitlab_service_errors:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n)[$__range:$__interval])\n/\nsum_over_time(\n  sum by(component) (\n    gitlab_service_ops:rate_1h{type=\"hosted-runners\", component=\"ci_runner_jobs\"}\n  )[$__range:$__interval])\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}