{
 "title": "Occurence SLAs",
 "tags": [
  "general",
  "slas",
  "service-levels"
 ],
 "time": { "from": "now-1M/M", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "webservice_weight", "query": "0,1,5" },
   { "name": "registry_weight", "query": "0,1,5" }
  ]
 },
 "panels": [
  { "title": "Overall GitLab availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Overall availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{type=\"registry\"}[$__range]) * $registry_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{type=\"webservice\"}[$__range]) * $webservice_weight\n  )\n)\n/\nsum(\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{type=\"registry\"}[$__range]) * $registry_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{type=\"webservice\"}[$__range]) * $webservice_weight\n  )\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    sum(\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{type=\"registry\"}[$__range]) * $registry_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{type=\"webservice\"}[$__range]) * $webservice_weight\n      )\n    )\n    /\n    sum(\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{type=\"registry\"}[$__range]) * $registry_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{type=\"webservice\"}[$__range]) * $webservice_weight\n      )\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Overall GitLab.com SLA over time period",
   "type": "timeseries",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum(\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{type=\"registry\"}[$__interval]) * $registry_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{type=\"webservice\"}[$__interval]) * $webservice_weight\n      )\n    )\n    /\n    sum(\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{type=\"registry\"}[$__interval]) * $registry_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{type=\"webservice\"}[$__interval]) * $webservice_weight\n      )\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "Overall SLA"
    }
   ]
  },
  {
   "title": "GitLab Primary Service Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "webservice availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{type=~\"webservice\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{type=~\"webservice\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{type=~\"webservice\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{type=~\"webservice\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "webservice SLA over time period",
   "type": "timeseries",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{type=~\"webservice\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{type=~\"webservice\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "webservice SLA"
    }
   ]
  },
  {
   "title": "registry availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{type=~\"registry\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{type=~\"registry\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{type=~\"registry\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{type=~\"registry\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "registry SLA over time period",
   "type": "timeseries",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{type=~\"registry\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{type=~\"registry\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "registry SLA"
    }
   ]
  }
 ]
}