{
 "title": "redis Service Overview",
 "tags": [
  "gitlab",
  "type:redis",
  "redis",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "redis Service Apdex",
   "type": "timeseries",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{type=\"redis\"}[$__interval])\n",
     "legendFormat": "redis apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"redis\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"redis\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{type=\"redis\"}[$__interval])\n",
     "legendFormat": "redis apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{type=\"redis\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"redis\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{type=\"redis\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"redis\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"redis\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"redis\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"redis\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "redis Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "redis Service Error Ratio",
   "type": "timeseries",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{type=\"redis\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "redis error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"redis\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"redis\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{type=\"redis\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "redis error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{type=\"redis\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"redis\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{type=\"redis\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{type=\"redis\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"redis\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{type=\"redis\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"redis\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{type=\"redis\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"redis\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{type=\"redis\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"redis\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "redis Service | Errors"
    }
   ]
  },
  {
   "title": "redis Service RPS - Requests per Second",
   "type": "timeseries",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{type=\"redis\"}[$__interval])\n",
     "legendFormat": "redis RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{type=\"redis\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{type=\"redis\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{type=\"redis\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{type=\"redis\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{type=\"redis\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "primary_server SLI RPS - Requests per Second",
   "type": "timeseries",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"primary_server\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "primary_server RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"primary_server\",type=\"redis\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "content": "### Description\n\nOperations on the Redis primary for Redis instance.\n\n"
  },
  {
   "title": "rails_redis_client SLI Apdex",
   "type": "timeseries",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_redis_client\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "rails_redis_client apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",type=\"redis\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",type=\"redis\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_redis_client\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "rails_redis_client apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"rails_redis_client\",type=\"redis\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",type=\"redis\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",type=\"redis\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",type=\"redis\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",type=\"redis\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",type=\"redis\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rails_redis_client SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "rails_redis_client SLI Error Ratio",
   "type": "timeseries",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"rails_redis_client\",type=\"redis\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_redis_client error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",type=\"redis\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",type=\"redis\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"rails_redis_client\",type=\"redis\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_redis_client error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"rails_redis_client\",type=\"redis\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",type=\"redis\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:confidence:ratio_5m{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Error SLI (lower 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:confidence:ratio_1h{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_errors:confidence:ratio_5m{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",type=\"redis\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_errors:confidence:ratio_1h{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",type=\"redis\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_errors:confidence:ratio_30m{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",type=\"redis\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_errors:confidence:ratio_6h{component=\"rails_redis_client\",confidence=\"98%\",type=\"redis\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",type=\"redis\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rails_redis_client SLI | Errors"
    }
   ]
  },
  {
   "title": "rails_redis_client SLI RPS - Requests per Second",
   "type": "timeseries",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"rails_redis_client\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "rails_redis_client RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"rails_redis_client\",type=\"redis\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "content": "### Description\n\nAggregation of all Redis operations issued from the Rails codebase\nthrough `Gitlab::Redis::Wrapper` subclasses.\n\n"
  },
  {
   "title": "redis SLI Apdex",
   "type": "timeseries",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"redis\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "redis apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",type=\"redis\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",type=\"redis\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"redis\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "redis apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"redis\",type=\"redis\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",type=\"redis\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:confidence:ratio_5m{component=\"redis\",confidence=\"98%\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "Apdex SLI (upper 98% confidence boundary)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:confidence:ratio_1h{component=\"redis\",confidence=\"98%\",type=\"redis\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:confidence:ratio_5m{component=\"redis\",confidence=\"98%\",type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",type=\"redis\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:confidence:ratio_1h{component=\"redis\",confidence=\"98%\",type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",type=\"redis\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:confidence:ratio_30m{component=\"redis\",confidence=\"98%\",type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",type=\"redis\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:confidence:ratio_6h{component=\"redis\",confidence=\"98%\",type=\"redis\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"redis\",type=\"redis\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "redis SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "redis SLI RPS - Requests per Second",
   "type": "timeseries",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"redis\",type=\"redis\"}[$__interval])\n",
     "legendFormat": "redis RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"redis\",type=\"redis\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: primary_server",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "primary_server RPS - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by () (\n  rate(redis_commands_processed_total{type=\"redis\"}[$__interval]) and on (instance) redis_instance_info{role=\"master\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "primary_server RPS - per instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (\n  rate(redis_commands_processed_total{instance!=\"\",type=\"redis\"}[$__interval]) and on (instance) redis_instance_info{role=\"master\"}\n)\n > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: rails_redis_client",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 rails_redis_client Latency - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitlab_redis_client_requests_duration_seconds_bucket{}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "rails_redis_client Errors - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_redis_client_exceptions_total{}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "rails_redis_client RPS - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_redis_client_requests_total{}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 rails_redis_client Latency - per type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,type) (\n    rate(gitlab_redis_client_requests_duration_seconds_bucket{type!=\"\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{type}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_redis_client Latency - per type",
     "type": "timeseries",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (type) (\n  rate(gitlab_redis_client_requests_duration_seconds_bucket{le=\"+Inf\",type!=\"\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (type) (\n    rate(gitlab_redis_client_requests_duration_seconds_bucket{le=\"0.5\",type!=\"\"}[$__interval])\n  )\n  +\n  sum by (type) (\n    rate(gitlab_redis_client_requests_duration_seconds_bucket{le=\"0.75\",type!=\"\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(type) group_left()\n  (\n    sum by () (\n  rate(gitlab_redis_client_requests_duration_seconds_bucket{le=\"+Inf\",type!=\"\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "rails_redis_client Errors - per type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type) (\n  rate(gitlab_redis_client_exceptions_total{type!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "rails_redis_client RPS - per type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type) (\n  rate(gitlab_redis_client_requests_total{type!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: redis",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 redis Latency - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitlab_cache_operation_duration_seconds_bucket{}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "redis RPS - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_cache_operation_duration_seconds_count{}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}