{
 "title": "sidekiq Service Overview",
 "tags": [
  "gitlab",
  "type:sidekiq",
  "sidekiq",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "shard",
    "query": "label_values(gitlab_component_shard_ops:rate_5m{type=\"sidekiq\"}, shard)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "sidekiq Service Apdex",
   "type": "timeseries",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"sidekiq\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{type=\"sidekiq\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"sidekiq\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{type=\"sidekiq\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{type=\"sidekiq\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"sidekiq\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{type=\"sidekiq\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"sidekiq\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{type=\"sidekiq\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"sidekiq\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{type=\"sidekiq\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",type=\"sidekiq\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "sidekiq Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "sidekiq Service Error Ratio",
   "type": "timeseries",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{type=\"sidekiq\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sidekiq error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"sidekiq\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"sidekiq\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{type=\"sidekiq\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sidekiq error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{type=\"sidekiq\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"sidekiq\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{type=\"sidekiq\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{type=\"sidekiq\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"sidekiq\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{type=\"sidekiq\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"sidekiq\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{type=\"sidekiq\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"sidekiq\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{type=\"sidekiq\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",type=\"sidekiq\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "sidekiq Service | Errors"
    }
   ]
  },
  {
   "title": "sidekiq Service RPS - Requests per Second",
   "type": "timeseries",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{type=\"sidekiq\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{type=\"sidekiq\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{type=\"sidekiq\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{type=\"sidekiq\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{type=\"sidekiq\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{shard=~\"$shard\",type=\"sidekiq\"}[$__interval]\n  )\n) by (component, shard)\n",
     "legendFormat": "{{ component }} component - {{ shard }} shard"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "sidekiq_execution SLI (By Shard) Apdex",
   "type": "timeseries",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_shard_apdex:ratio_5m{component=\"sidekiq_execution\",shard=~\"$shard\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_execution - {{ shard }} shard apdex"
    },
    {
     "expr": "(1 - 6 * (1 - (\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",shard=\"\",type=\"sidekiq\"})\n)\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget) - {{ shard }} shard"
    },
    {
     "expr": "(1 - 14.4 * (1 - (\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",shard=\"\",type=\"sidekiq\"})\n)\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget) - {{ shard }} shard"
    }
   ]
  },
  {
   "title": "sidekiq_execution SLI (By Shard) Error Ratio",
   "type": "timeseries",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_shard_errors:ratio_5m{component=\"sidekiq_execution\",shard=~\"$shard\",type=\"sidekiq\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sidekiq_execution - {{ shard }} shard error ratio"
    },
    {
     "expr": "(6 * (\navg by (shard) (slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",shard=\"\",type=\"sidekiq\"})\n)\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget) - {{ shard }} shard"
    },
    {
     "expr": "(14.4 * (\navg by (shard) (slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",shard=\"\",type=\"sidekiq\"})\n)\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget) - {{ shard }} shard"
    }
   ]
  },
  {
   "title": "sidekiq_execution SLI (By Shard) RPS - Requests per Second",
   "type": "timeseries",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_shard_ops:rate_5m{component=\"sidekiq_execution\",shard=~\"$shard\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_execution - {{ shard }} shard RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "content": "### Description\n\nSidekiq job completion timings.\n\n This is the time it takes for jobs to execute once they've been picked up by a worker.\n A dip in this apdex indicates that jobs are not completing within the expected time frame.  This can be caused by many possibilities, including:\n 1. Resource contention in the workers (e.g. thread contention for CPU time, due to high concurrency),\n 2. Resource contention in other resources (e.g. database CPU saturation),\n 3. Poorly performing worker code or queries\n\n Satisfied queue latency thresholds are defined in the application by urgency.\n See <https://docs.gitlab.com/development/sidekiq/worker_attributes/#job-urgency>\n\n 1. 10s for high urgency jobs.\n 2. 5m for low urgency jobs.\n 3. 5m for throttled jobs.\n\n"
  },
  {
   "title": "sidekiq_queueing SLI (By Shard) Apdex",
   "type": "timeseries",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_shard_apdex:ratio_5m{component=\"sidekiq_queueing\",shard=~\"$shard\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_queueing - {{ shard }} shard apdex"
    },
    {
     "expr": "(1 - 6 * (1 - (\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing\",shard=\"\",type=\"sidekiq\"})\n)\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget) - {{ shard }} shard"
    },
    {
     "expr": "(1 - 14.4 * (1 - (\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing\",shard=~\"$shard\",type=\"sidekiq\"})\nor\navg by (shard) (slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_queueing\",shard=\"\",type=\"sidekiq\"})\n)\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget) - {{ shard }} shard"
    }
   ]
  },
  {
   "title": "sidekiq_queueing SLI (By Shard) RPS - Requests per Second",
   "type": "timeseries",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_shard_ops:rate_5m{component=\"sidekiq_queueing\",shard=~\"$shard\",type=\"sidekiq\"}[$__interval])\n",
     "legendFormat": "sidekiq_queueing - {{ shard }} shard RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nSidekiq queue latency per shard.\n\nThis is the time it takes for jobs to be picked up in the queue.\nA dip in this Apdex indicates that the queues are saturated and cannot process the backlog of jobs fast enough.\n\nSatisfied queue latency thresholds are defined in the application by urgency.\nSee <https://docs.gitlab.com/development/sidekiq/worker_attributes/#job-urgency>\n\n1. 10s for high urgency jobs.\n2. 1m for low urgency jobs.\n3. throttled jobs do not have an expected duration.\n\n"
  },
  {
   "title": "🔬 SLI Detail: sidekiq_execution",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "sidekiq_execution Errors - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_sli_sidekiq_execution_error_total{shard=~\"$shard\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_sli_sidekiq_execution_total{shard=~\"$shard\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per feature_category",
     "type": "timeseries",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      rate(gitlab_sli_sidekiq_execution_apdex_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n    )\n    -\n    sum by (feature_category) (\n      rate(gitlab_sli_sidekiq_execution_apdex_success_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      rate(gitlab_sli_sidekiq_execution_apdex_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per feature_category",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  rate(gitlab_sli_sidekiq_execution_error_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per feature_category",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  rate(gitlab_sli_sidekiq_execution_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per worker",
     "type": "timeseries",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (worker) (\n      rate(gitlab_sli_sidekiq_execution_apdex_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n    )\n    -\n    sum by (worker) (\n      rate(gitlab_sli_sidekiq_execution_apdex_success_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n    )\n  )\n  / ignoring (worker) group_left()\n  (\n    sum by () (\n      rate(gitlab_sli_sidekiq_execution_apdex_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per worker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (worker) (\n  rate(gitlab_sli_sidekiq_execution_error_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per worker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (worker) (\n  rate(gitlab_sli_sidekiq_execution_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: sidekiq_queueing",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "sidekiq_queueing RPS - Overall",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_sli_sidekiq_queueing_apdex_total{shard=~\"$shard\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing Latency - per feature_category",
     "type": "timeseries",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      rate(gitlab_sli_sidekiq_queueing_apdex_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n    )\n    -\n    sum by (feature_category) (\n      rate(gitlab_sli_sidekiq_queueing_apdex_success_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      rate(gitlab_sli_sidekiq_queueing_apdex_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing RPS - per feature_category",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  rate(gitlab_sli_sidekiq_queueing_apdex_total{feature_category!=\"\",shard=~\"$shard\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_queueing Latency - per worker",
     "type": "timeseries",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (worker) (\n      rate(gitlab_sli_sidekiq_queueing_apdex_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n    )\n    -\n    sum by (worker) (\n      rate(gitlab_sli_sidekiq_queueing_apdex_success_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n    )\n  )\n  / ignoring (worker) group_left()\n  (\n    sum by () (\n      rate(gitlab_sli_sidekiq_queueing_apdex_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "sidekiq_queueing RPS - per worker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (worker) (\n  rate(gitlab_sli_sidekiq_queueing_apdex_total{shard=~\"$shard\",worker!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "excluded_sidekiq_kube_container_rss_request component saturation: Excluded Sidekiq Kube Container Memory Utilization (RSS)",
     "type": "timeseries",
     "description": "Records the total anonymous (unevictable) memory utilization for containers for this\nservice, as a percentage of the memory request as configured through Kubernetes.\n\nThis is computed using the container's resident set size (RSS), as opposed to\nkube_container_memory which uses the working set size. For our purposes, RSS is the\nbetter metric as cAdvisor's working set calculation includes pages from the\nfilesystem cache that can (and will) be evicted before the OOM killer kills the\ncgroup.\n\nA container's RSS (anonymous memory usage) is still not precisely what the OOM\nkiller will use, but it's a better approximation of what the container's workload is\nactually using. RSS metrics can, however, be dramatically inflated if a process in\nthe container uses MADV_FREE (lazy-free) memory. RSS will include the memory that is\navailable to be reclaimed without a page fault, but not currently in use.\n\nThe most common case of OOM kills is for anonymous memory demand to overwhelm the\ncontainer's memory request. On swapless hosts, anonymous memory cannot be evicted from\nthe page cache, so when a container's memory usage is mostly anonymous pages, the\nonly remaining option to relieve memory pressure may be the OOM killer.\n\nAs container RSS approaches container memory request, OOM kills become much more\nlikely. Consequently, this ratio is a good leading indicator of memory saturation\nand OOM risk.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(container,deployment,pod,shard,type) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        container_memory_rss:labeled{container!=\"\", container!=\"POD\", shard=\"gitaly-throttled\", type=\"sidekiq\"}\n        unless on(pod) (\n          kube_pod_labels:labeled{label_gitlab_com_exclude_saturation_point=~\"(^|.*[.])kube_container_rss_request([.].*|$)\", type=\"sidekiq\"}\n        )\n      )\n      / on(container,deployment,pod,shard,type) group_left()\n      max by(container,deployment,pod,shard,type) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", resource=\"memory\", shard=\"gitaly-throttled\", type=\"sidekiq\"} > 0\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }} {{ deployment }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{type=\"sidekiq\", component=\"excluded_sidekiq_kube_container_rss_request\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{type=\"sidekiq\", component=\"excluded_sidekiq_kube_container_rss_request\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{type=\"sidekiq\", component=\"excluded_sidekiq_kube_container_rss_request\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"excluded_sidekiq_kube_container_rss_request\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"excluded_sidekiq_kube_container_rss_request\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "timeseries",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(container,pod,shard,type) (\n  clamp_min(\n    clamp_max(\n      sum by (container,pod,shard,type) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", type=\"sidekiq\"}[5m])\n        unless on(pod) (\n          kube_pod_labels:labeled{label_gitlab_com_exclude_saturation_point=~\"(^|.*[.])kube_container_cpu_limit([.].*|$)\", type=\"sidekiq\"}\n        )\n      )\n      /\n      sum by(container,pod,shard,type) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", type=\"sidekiq\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", type=\"sidekiq\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{type=\"sidekiq\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{type=\"sidekiq\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{type=\"sidekiq\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory_request component saturation: Kube Container Memory Utilization",
     "type": "timeseries",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(container,deployment,pod,shard,type) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", type=\"sidekiq\"}\n        unless on(pod) (\n          kube_pod_labels:labeled{label_gitlab_com_exclude_saturation_point=~\"(^|.*[.])kube_container_memory_request([.].*|$)\", type=\"sidekiq\"}\n        )\n      )\n      / on(container,deployment,pod,shard,type) group_left()\n      max by(container,deployment,pod,shard,type) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", resource=\"memory\", type=\"sidekiq\"} > 0\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }} {{ deployment }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{type=\"sidekiq\", component=\"kube_container_memory_request\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{type=\"sidekiq\", component=\"kube_container_memory_request\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{type=\"sidekiq\", component=\"kube_container_memory_request\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory_request\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory_request\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_rss_limit component saturation: Kube Container Memory Over-Utilization (RSS)",
     "type": "timeseries",
     "description": "Records the total anonymous (unevictable) memory utilization for containers for this\nservice, as a percentage of the memory limit as configured through Kubernetes.\n\nThis is computed using the container's resident set size (RSS), as opposed to\nkube_container_memory which uses the working set size. For our purposes, RSS is the\nbetter metric as cAdvisor's working set calculation includes pages from the\nfilesystem cache that can (and will) be evicted before the OOM killer kills the\ncgroup.\n\nA container's RSS (anonymous memory usage) is still not precisely what the OOM\nkiller will use, but it's a better approximation of what the container's workload is\nactually using. RSS metrics can, however, be dramatically inflated if a process in\nthe container uses MADV_FREE (lazy-free) memory. RSS will include the memory that is\navailable to be reclaimed without a page fault, but not currently in use.\n\nThe most common case of OOM kills is for anonymous memory demand to overwhelm the\ncontainer's memory limit. On swapless hosts, anonymous memory cannot be evicted from\nthe page cache, so when a container's memory usage is mostly anonymous pages, the\nonly remaining option to relieve memory pressure may be the OOM killer.\n\nAs container RSS goes over the container memory request and approaches\ncontainer memory limit, OOM kills become much more likely. Consequently,\nthis ratio is a good leading indicator of memory saturation and OOM risk.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(container,deployment,pod,shard,type) (\n  clamp_min(\n    clamp_max(\n      (\n        container_memory_rss:labeled{container!=\"\", container!=\"POD\", type=\"sidekiq\"}\n        unless on(pod) (\n          kube_pod_labels:labeled{label_gitlab_com_exclude_saturation_point=~\"(^|.*[.])kube_container_rss_limit([.].*|$)\", type=\"sidekiq\"}\n        )\n      )\n      / on(container,deployment,pod,shard,type) group_left()\n      max by(container,deployment,pod,shard,type) (\n        kube_pod_container_resource_limits:labeled{container!=\"\", resource=\"memory\", type=\"sidekiq\"} > 0\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }} {{ deployment }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{type=\"sidekiq\", component=\"kube_container_rss_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{type=\"sidekiq\", component=\"kube_container_rss_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{type=\"sidekiq\", component=\"kube_container_rss_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_rss_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_rss_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "sidekiq_kube_container_rss_request component saturation: Sidekiq Kube Container Memory Utilization (RSS)",
     "type": "timeseries",
     "description": "Records the total anonymous (unevictable) memory utilization for containers for this\nservice, as a percentage of the memory request as configured through Kubernetes.\n\nThis is computed using the container's resident set size (RSS), as opposed to\nkube_container_memory which uses the working set size. For our purposes, RSS is the\nbetter metric as cAdvisor's working set calculation includes pages from the\nfilesystem cache that can (and will) be evicted before the OOM killer kills the\ncgroup.\n\nA container's RSS (anonymous memory usage) is still not precisely what the OOM\nkiller will use, but it's a better approximation of what the container's workload is\nactually using. RSS metrics can, however, be dramatically inflated if a process in\nthe container uses MADV_FREE (lazy-free) memory. RSS will include the memory that is\navailable to be reclaimed without a page fault, but not currently in use.\n\nThe most common case of OOM kills is for anonymous memory demand to overwhelm the\ncontainer's memory request. On swapless hosts, anonymous memory cannot be evicted from\nthe page cache, so when a container's memory usage is mostly anonymous pages, the\nonly remaining option to relieve memory pressure may be the OOM killer.\n\nAs container RSS approaches container memory request, OOM kills become much more\nlikely. Consequently, this ratio is a good leading indicator of memory saturation\nand OOM risk.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(container,deployment,pod,shard,type) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      (\n        container_memory_rss:labeled{container!=\"\", container!=\"POD\", shard!~\"gitaly-throttled\", type=\"sidekiq\"}\n        unless on(pod) (\n          kube_pod_labels:labeled{label_gitlab_com_exclude_saturation_point=~\"(^|.*[.])kube_container_rss_request([.].*|$)\", type=\"sidekiq\"}\n        )\n      )\n      / on(container,deployment,pod,shard,type) group_left()\n      max by(container,deployment,pod,shard,type) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", resource=\"memory\", shard!~\"gitaly-throttled\", type=\"sidekiq\"} > 0\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }} {{ deployment }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{type=\"sidekiq\", component=\"sidekiq_kube_container_rss_request\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{type=\"sidekiq\", component=\"sidekiq_kube_container_rss_request\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{type=\"sidekiq\", component=\"sidekiq_kube_container_rss_request\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"sidekiq_kube_container_rss_request\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"sidekiq_kube_container_rss_request\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}