{
 "title": "source-code-management: Mirrors",
 "tags": [
  "managed",
  "source-code-management"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall Mirror Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Mirror Updates per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_updated_very_recently\"}/30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project Mirror Updates Overdue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_ready_to_sync\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_behind_schedule\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mirrors Not Updated in 30 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_not_updated_recently\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting Delays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_repository_mirror_waiting_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pull Mirroring Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_repository_mirror_update_duration_seconds_bucket{}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mirror Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Scheduled or Started (Capacity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_scheduled_or_started\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_scheduled\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_started\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Running Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "UpdateAllMirrorsWorker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_running_jobs{worker=\"UpdateAllMirrorsWorker\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ProjectImportScheduleWorker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_running_jobs{worker=\"ProjectImportScheduleWorker\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RepositoryUpdateMirrorWorker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_running_jobs{worker=\"RepositoryUpdateMirrorWorker\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processed Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Jobs Processed per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_completion_count{worker=~\"UpdateAllMirrorsWorker|ProjectImportScheduleWorker|RepositoryUpdateMirrorWorker\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Failed per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_failed_total{worker=~\"UpdateAllMirrorsWorker|ProjectImportScheduleWorker|RepositoryUpdateMirrorWorker\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}