{
 "title": "[NEW][04] Postgres Wait sampling dashboard",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(node_exporter_build_info,type)"
    }
   },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(node_exporter_build_info{tier=\"db\", type=\"$type\", environment=\"$environment\"},fqdn)"
    }
   },
   {
    "name": "wait_type",
    "label": "wait type",
    "query": {
     "query": "label_values(pg_wait_sampling_count{fqdn=\"$fqdn\"},wait_type)"
    }
   },
   {
    "name": "wait_event",
    "label": "wait_event",
    "query": {
     "query": "label_values(pg_wait_sampling_count{fqdn=\"$fqdn\", wait_type=~\"$wait_type\"},wait_event)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_replication_is_replica{env=\"$environment\",fqdn=\"$fqdn\"}",
     "legendFormat": "role"
    }
   ]
  },
  { "title": "ASH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Active session history (ASH). Unfiltered ",
   "type": "timeseries",
   "description": "Graph based on pg_wait_sampling_profile view of https://github.com/postgrespro/pg_wait_sampling extension.\n\nOn vertical Axis is number of backends with specific wait event type  \n\n- Client and Activity events are not shown by default, but can be done visible by clicking on them in the legend list.\n- CPU or Uncategorised wait event means backend either is being executed on CPU or waiting for CPU or some other wait that is not known yet",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sessions" } },
   "targets": [
    {
     "expr": "(sum by (wait_type) (rate(pg_wait_sampling_count{fqdn=\"$fqdn\"}[$__rate_interval])))/100",
     "legendFormat": "{{wait_type}}"
    },
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{fqdn=\"$fqdn\",mode=\"idle\"})",
     "legendFormat": "CPU count"
    }
   ]
  },
  {
   "title": "ASH. Filter by wait type: $wait_type",
   "type": "timeseries",
   "description": "Graph based on pg_wait_sampling_profile view of https://github.com/postgrespro/pg_wait_sampling extension.\n\nOn vertical Axis is number of backends with specific wait event type  \n\n- Client and Activity events are not shown by default, but can be done visible by clicking on them in the legend list.\n- CPU or Uncategorised wait event means backend either is being executed on CPU or waiting for CPU or some other wait that is not known yet",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sessions" } },
   "targets": [
    {
     "expr": "(sum by (wait_type,wait_event) (irate(pg_wait_sampling_count{fqdn=\"$fqdn\", wait_type=~\"$wait_type\"}[$__rate_interval])))/100",
     "legendFormat": "{{wait_type}} - {{wait_event}}"
    }
   ]
  },
  {
   "title": "ASH by queryid. Filter by wait type: $wait_type, wait event: $wait_event ",
   "type": "timeseries",
   "description": "Graph based on pg_wait_sampling_profile view of https://github.com/postgrespro/pg_wait_sampling extension.\n\nOn vertical Axis is number of backends with specific wait event type  \n\n- Client and Activity events are not shown by default, but can be done visible by clicking on them in the legend list.\n- CPU or Uncategorised wait event means backend either is being executed on CPU or waiting for CPU or some other wait that is not known yet",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "sessions" } },
   "targets": [
    {
     "expr": "(sum by (queryid) (irate(pg_wait_sampling_count{fqdn=\"$fqdn\",wait_type=~\"${wait_type}\",wait_event=~\"${wait_event}\"}[$__rate_interval])))/100 > 0.01",
     "legendFormat": "{{queryid}}"
    }
   ]
  }
 ]
}