// This file is autogenerated using scripts/generate-service-dashboards
// Please feel free to customize this file.
local memorystoreRedisCommon = import 'gitlab-dashboards/memorystore_redis_common_graphs.libsonnet';

memorystoreRedisCommon.memorystoreRedisDashboard('memorystore-redis-tracechunks')
.overviewTrailer()
