// This file is autogenerated using scripts/generate-service-dashboards
// Please feel free to customize this file.
local serviceDashboard = import 'gitlab-dashboards/service_dashboard.libsonnet';

serviceDashboard.overview('pd-event-logger-7760xa')
.overviewTrailer()
