# DO NOT MANUALLY EDIT; Run ./scripts/update-asdf-version-variables.sh to update this
variables:
  GL_ASDF_AMTOOL_VERSION: "0.32.0"
  GL_ASDF_GO_JSONNET_VERSION: "0.22.0"
  GL_ASDF_GOLANG_VERSION: "1.26.2"
  GL_ASDF_JB_VERSION: "0.6.0"
  GL_ASDF_JSONNET_TOOL_VERSION: "1.19"
  GL_ASDF_KUBECONFORM_VERSION: "0.7.0"
  GL_ASDF_KUBECTL_VERSION: "1.35.3"
  GL_ASDF_MIMIRTOOL_VERSION: "3.0.4"
  GL_ASDF_NODEJS_VERSION: "24.15.0"
  GL_ASDF_ORAS_VERSION: "1.3.2"
  GL_ASDF_PRE_COMMIT_VERSION: "4.5.1"
  GL_ASDF_RUBY_VERSION: "4.0.2"
  GL_ASDF_SHELLCHECK_VERSION: "0.11.0"
  GL_ASDF_SHFMT_VERSION: "3.13"
  GL_ASDF_TERRAFORM_VERSION: "1.14.8"
  GL_ASDF_VAULT_VERSION: "1.21.4"
  GL_ASDF_YQ_VERSION: "4.52.5"
