// This file is autogenerated using scripts/generate-service-dashboards
// Please feel free to customize this file.
local runwayPostgresCommon = import 'gitlab-dashboards/runway_postgres_common_graphs.libsonnet';

runwayPostgresCommon.runwayPostgresDashboard('runway-db-example')
.overviewTrailer()
