{
 "title": "bundle-uri usage",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "env",
    "label": "environment",
    "query": {
     "query": "label_values(gitaly_bundle_generation_bytes_total,environment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Bundle data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Generation latency percentile",
   "type": "timeseries",
   "description": "This graph shows different percentiles for the bundle generation latency.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_bundle_generation_seconds_bucket{env=~\"$env\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitaly_bundle_generation_seconds_bucket{environment=~\"$env\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gitaly_bundle_generation_seconds_bucket{environment=~\"$env\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gitaly_bundle_generation_seconds_bucket{environment=~\"$env\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Bundles generated per host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(fqdn) (increase(gitaly_bundle_generation_seconds_count{env=\"$env\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(gitaly_bundle_generation_seconds_count{environment=\"$env\"}[$__range]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Bytes written to storage per host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(fqdn) (increase(gitaly_bundle_generation_bytes_total{env=\"$env\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(gitaly_bundle_generation_bytes_total{environment=\"$env\"}[$__range]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Rate of bundles generated per seconds",
   "type": "timeseries",
   "description": "A bundle is considered generated when it is complete, not when it starts.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(fqdn) (rate(gitaly_bundle_generation_seconds_count{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes written to cloud storage throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(fqdn) (increase(gitaly_bundle_generation_bytes_total{env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  { "title": "Strategy's monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Strategy's state memory usage",
   "type": "gauge",
   "description": "This graph is very dumb and prone to incorrect data. It simply calculates the nimber of items in the state * the size in byte of a state item: https://gitlab.com/gitlab-org/gitaly/-/blob/master/internal/bundleuri/strategy_occurences.go?ref_type=heads#L53. This graph can become invalid if the state item changes. For the gauge visualization, the max has been put arbitrarily to 5Mib. ",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gitaly_bundle_strategy_occurrence_state_len{env=\"$env\"}) * 56",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of items in strategy state",
   "type": "timeseries",
   "description": "This graph shows the number of items in the in-memory state of the strategy. This graph is helpful to see if the state is having memory leaks issue. One item is 56 byte: https://gitlab.com/gitlab-org/gitaly/-/blob/master/internal/bundleuri/strategy_occurences.go?ref_type=heads#L53",
   "gridPos": { "h": 10, "w": 17, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "gitaly_bundle_strategy_occurrence_state_len{env=\"$env\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Gitaly PostUploadPack CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(fqdn) (irate(gitaly_command_cpu_seconds_total{grpc_method=\"PostUploadPackWithSidechannel\", env=\"$env\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}