// This file is autogenerated using scripts/generate-service-dashboards
// Please feel free to customize this file.
local runwayRedisCommon = import 'gitlab-dashboards/runway_redis_common_graphs.libsonnet';

runwayRedisCommon.runwayRedisDashboard('runway-redis-example')
.overviewTrailer()
