#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

REPO_DIR=$(
  cd "$(dirname "${BASH_SOURCE[0]}")/.."
  pwd
)

UPSTREAM_PROJECT='gitlab-org%2Fgitlab'
UPSTREAM_PATH='config/user_experience_slis'
UPSTREAM_REF='master'
DEST_DIR="${REPO_DIR}/${UPSTREAM_PATH}"

GITLAB_API_BASE='https://gitlab.com/api/v4'

if ! hash curl 2>/dev/null; then
  echo >&2 "curl not found, please install it"
  exit 1
fi

if ! hash jq 2>/dev/null; then
  echo >&2 "jq not found, please install it via: brew install jq (macOS) or apt-get install jq (Linux)"
  exit 1
fi

echo "Fetching file list from ${UPSTREAM_PROJECT}/${UPSTREAM_PATH} ..."

files=$(curl --silent --fail --show-error \
  "${GITLAB_API_BASE}/projects/${UPSTREAM_PROJECT}/repository/tree?path=${UPSTREAM_PATH}&ref=${UPSTREAM_REF}&per_page=100" |
  jq -r '.[] | select(.type == "blob") | .path')

mkdir -p "${DEST_DIR}"

index_file="${DEST_DIR}/index.yml"
echo "Fetching SLI files and generating index.yml ..."
{
  printf '# This file is autogenerated by scripts/sync-user-experience-slis.sh\n'
  printf '# Do not edit manually — re-run the script to update.\n'
  while IFS= read -r file_path; do
    filename=$(basename "${file_path}")
    encoded_path="${file_path//\//%2F}"

    echo "  Fetching ${file_path} ..." >&2

    raw_content=$(curl --silent --fail --show-error \
      "${GITLAB_API_BASE}/projects/${UPSTREAM_PROJECT}/repository/files/${encoded_path}/raw?ref=${UPSTREAM_REF}")

    sli_id="$(basename "${filename}" .yml)"
    feature_category="$(printf '%s\n' "${raw_content}" | grep '^feature_category:' | sed 's/.*:[[:space:]]*//' | tr -d '"')"
    urgency="$(printf '%s\n' "${raw_content}" | grep '^urgency:' | sed 's/.*:[[:space:]]*//' | tr -d '"')"
    printf '%s:\n  feature_category: %s\n  urgency: %s\n' \
      "${sli_id}" "${feature_category}" "${urgency}"
  done <<<"${files}"
} >"${index_file}"
echo "  -> ${index_file}"

echo "Done. ${index_file} is up to date."
