#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'
require_relative '../lib/monitored_services'

begin
  service_names = MonitoredServices.get_service_names
  invalid_services = service_names.select { |name| !MonitoredServices.has_dashboard?(name) }
  return if invalid_services.empty?

  puts "The following services do not have dashboards:"
  puts invalid_services
  exit 1
rescue StandardError => e
  warn [e.message, *e.backtrace].join("\n")
  exit 1
end
