{
 "title": "Database Capacity and Saturation Analysis -  7 Days",
 "tags": [
  "Postgresql",
  "unmanaged"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "primary_name",
    "query": "patroni-v12-05-db-gprd.c.gitlab-production.internal"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"gitlabhq_production\", environment=\"gprd\", tier=\"db\", type=\"patroni\"}[$__rate_interval])",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{environment=\"gprd\", tier=\"db\", type=\"patroni\"}",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Context Switches - Primary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{fqdn=\"$primary_name\"}[$__rate_interval])",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  { "title": "IO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "IO Wait Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{environment=\"gprd\", tier=\"db\", type=\"patroni\", device=~\"sdb\"}[$__rate_interval])) by (fqdn)",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "IO Wait Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{environment=\"gprd\", tier=\"db\", type=\"patroni\", device=~\"sdb\"}[$__rate_interval])) by (fqdn) ",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "IO Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{environment=\"gprd\", tier=\"db\", type=\"patroni\", device=~\"sdb\"}[$__rate_interval]) ",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~ \"node_filesystem_size.*\", environment=\"gprd\", tier=\"db\", type=\"patroni\", mountpoint=\"/var/opt/gitlab\"} - {__name__=~\"node_filesystem_free.*\",environment=\"gprd\", tier=\"db\", type=\"patroni\", mountpoint=\"/var/opt/gitlab\"}",
     "legendFormat": "{{ fqdn }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Reads Bytes/Sec - Primary Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{fqdn=\"$primary_name\", device!~\"dm.*\"}[$__rate_interval])",
     "legendFormat": "{{ fqdn }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes/Sec - Primary Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{fqdn=\"$primary_name\", device!~\"dm.*\"}[10m])",
     "legendFormat": "{{ fqdn }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Reads Ops/Sec - Primary Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{fqdn=\"$primary_name\", device!~\"dm.*\"}[$__rate_interval])",
     "legendFormat": "{{ fqdn }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Write Ops/Sec - Primary Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{fqdn=\"$primary_name\", device!~\"dm.*\"}[$__rate_interval])",
     "legendFormat": "{{ fqdn }} - {{ device }}"
    }
   ]
  },
  { "title": "PGBouncer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "PGbouncer Web-API - Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{fqdn=~\"pgbouncer-01-db-gprd.c.gitlab-production.internal|pgbouncer-02-db-gprd.c.gitlab-production.internal|pgbouncer-03-db-gprd.c.gitlab-production.internal\",mode=\"user\"}[$__rate_interval])",
     "legendFormat": "{{ fqdn }} - CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "PGBouncer Sidekiq - Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{fqdn=~\"pgbouncer-sidekiq-01-db-gprd.c.gitlab-production.internal|pgbouncer-sidekiq-02-db-gprd.c.gitlab-production.internal|pgbouncer-sidekiq-03-db-gprd.c.gitlab-production.internal\",mode=\"user\"}[$__rate_interval])",
     "legendFormat": "{{ fqdn }} - CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "PGBouncer Component Average CPU Saturation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"gprd\", stage=\"main\", type=\"pgbouncer\", component=\"single_node_cpu\"}[$__rate_interval]\n      )\n    ) by (component)\n  ,1)\n,0)",
     "legendFormat": "{{ component }}"
    }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Network Bytes Received - Primary Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\", fqdn=\"$primary_name\"}[$__rate_interval])",
     "legendFormat": "{{ fqdn }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Network Bytes Sent - Primary Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\", fqdn=\"$primary_name\"}[$__rate_interval])",
     "legendFormat": "{[ fqdn }} - {{ device }}"
    }
   ]
  }
 ]
}