{
 "title": "pgbouncer Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "environment", "query": "gprd,gstg" }
  ]
 },
 "panels": [
  {
   "title": "Dedicated pgbouncers for read/write traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Backend connections (sidekiq)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_server_active_connections{database=\"gitlabhq_production_sidekiq\", type=\"pgbouncer\", environment=\"$environment\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Waiting Client Connections (sidekiq)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer_pools_client_waiting_connections{type=\"pgbouncer\", database=\"gitlabhq_production_sidekiq\", environment=\"$environment\"}[$__interval])  ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fqdn={{ fqdn }},database={{ database}}, user={{ user }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend connections (web)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_server_active_connections{database=\"gitlabhq_production\", type=\"pgbouncer\", environment=\"$environment\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Waiting Client Connections (web)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer_pools_client_waiting_connections{type=\"pgbouncer\", database=\"gitlabhq_production\", environment=\"$environment\"}[$__interval])  ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fqdn={{ fqdn }},database={{ database}}, user={{ user }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Complete overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer_pools_client_active_connections{environment=\"$environment\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fqdn={{ fqdn }},database={{ database}}, user={{ user }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Waiting Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer_pools_client_waiting_connections{environment=\"$environment\"}[$__interval])  ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fqdn={{ fqdn }},database={{ database}}, user={{ user }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer_pools_server_active_connections{environment=\"$environment\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "sv_active (fqdn={{ fqdn }},database={{ database}}, user={{ user }})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer_pools_client_maxwait_seconds{environment=\"$environment\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fqdn={{ fqdn }},database={{ database}}, user={{ user }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP Problems",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_ListenDrops{environment=\"$environment\",tier=\"db\"}[$__interval]) * -1",
     "legendFormat": "TCP Drops {{fqdn}}"
    },
    {
     "expr": "rate(node_netstat_TcpExt_ListenOverflows{environment=\"$environment\",tier=\"db\"}[$__interval])",
     "legendFormat": "TCP Overflow {{fdqn}}"
    }
   ]
  }
 ]
}