{
 "title": "PostgreSQL Backups",
 "tags": [
  "postgresql",
  "unmanaged"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(push_time_seconds,env)"
    }
   },
   { "name": "history_days", "label": "history", "query": "5" },
   {
    "name": "type",
    "query": "label_values(up{tier=\"db\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Last base backup host ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($history_days, push_time_seconds{env=\"$environment\",job=\"scrapeConfig/monitoring/prometheus-agent-pushgateway\",type=\"$type\"})"
    }
   ]
  },
  {
   "title": "Last Successful Base Backup Time ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(push_time_seconds{environment=\"$environment\",job=\"scrapeConfig/monitoring/prometheus-agent-pushgateway\",status=\"1\",type=\"$type\"})*1000"
    }
   ]
  },
  {
   "title": "Last Failed Base Backup Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(push_time_seconds{environment=\"$environment\",job=\"scrapeConfig/monitoring/prometheus-agent-pushgateway\",status=\"-1\",type=\"$type\"})*1000"
    }
   ]
  },
  {
   "title": "Seconds Since Last WAL Archicve(WAL-G)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(walg_backup_last_completed_time_seconds{environment=\"$environment\",type=\"$type\"})"
    }
   ]
  },
  {
   "title": "WAL-G Completed Per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(walg_backup_completed_count{environment=\"$environment\", prog=\"walg.mtail\",type=\"$type\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Base Backup Duration ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "\nlabel_replace(push_time_seconds{environment=\"$environment\",job='walg-basebackup',status=\"1\",type=\"$type\"}> (time()-$history_days*24*60*60), \"newid\", \"$1\", \"id\", \".*_(.*)\")\n- ignoring(status) label_replace(push_time_seconds{environment=\"$environment\",job='walg-basebackup',status=\"0\",type=\"$type\"}> (time()-$history_days*24*60*60),\"newid\", \"$1\", \"id\", \".*_(.*)\") ",
     "legendFormat": "{{newid}}"
    }
   ]
  }
 ]
}