{
 "title": "PostgreSQL Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "gprd,gstg,dr,db-integration,db-benchmarking"
   },
   {
    "name": "type",
    "query": "patroni, postgres11, postgres-delayed, postgres-archive, patroni-ci, patroni-registry,patroni-sec"
   }
  ]
 },
 "panels": [
  { "title": "Health & Alerts ($type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "type" },
  {
   "title": "Nodes Currently Up",
   "type": "stat",
   "description": "The number of nodes currently in the \"Up\" state.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{env=\"$environment\",type=\"$type\",job=\"scrapeConfig/monitoring/prometheus-agent-node-exporter-gce\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Health Past 24h",
   "type": "stat",
   "description": "The percentage of time no alerts were sent out.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(pg_up{env=\"$environment\",type=\"$type\"}[1d]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Health Past 7d",
   "type": "stat",
   "description": "The percentage of time no alerts were sent out.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(pg_up{environment=\"$environment\", type=\"$type\"}[1w]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ALERTS{alertname=~\"PostgreSQL.*\",environment=\"$environment\",alertstate=\"firing\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Overview ($type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "type" },
  {
   "title": "Primary Total Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_activity_count{env=\"$environment\",datname=\"gitlabhq_production\", tier=\"db\", type=\"$type\"} and on(instance) pg_replication_is_replica==0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary Active Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_activity_count{env=\"$environment\",datname=\"gitlabhq_production\", tier=\"db\", type=\"$type\", state=\"active\"} and ON(instance) pg_replication_is_replica{env=\"$environment\", tier=\"db\", type=\"$type\"}==0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",type=\"$type\"} and on (fqdn) pg_replication_is_replica{env=\"$environment\",type=\"$type\"}==0\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replica CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",type=\"$type\"} and on (fqdn) pg_replication_is_replica{env=\"$environment\",type=\"$type\"}==1\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication Lag Size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_replication_pg_xlog_location_diff{environment=\"$environment\", tier=\"db\", type=\"$type\"} and on (instance) pg_replication_is_replica==0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes & Transactions ($type)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "type"
  },
  {
   "title": "Process Activity Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg_over_time(pg_stat_activity_count{datname=\"gitlabhq_production\", env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} - {{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process Activity Total by Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum(avg_over_time(pg_stat_activity_count{datname=\"gitlabhq_production\", env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"gitlabhq_production\", env=\"$environment\", tier=\"db\", type=\"$type\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"gitlabhq_production\", environment=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])",
     "legendFormat": "{{fqdn}} rolled back"
    }
   ]
  },
  { "title": "Errors and Locks ($type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "type" },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(postgresql_errors_total{env=\"$environment\"}[$__rate_interval]) * 60) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PGBouncer Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_errors_count{env=\"$environment\",type=\"$type\",errmsg!~\"invalid command.*\"}[$__rate_interval]) > 0 * 60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}: {{errmsg}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slow Lock Acquires",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(postgresql_lock_waits_total{env=\"$environment\", type=\"$type\"}[$__rate_interval]) * 60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} on {{locktype}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Locks across all hosts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(pg_locks_count{env=\"$environment\", type=\"$type\"}[$__rate_interval]) * 60) by (mode)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Load ($type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "type" },
  {
   "title": "DB CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(instance:node_cpu_utilization:ratio{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Database Host Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(node_load1{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Storage & Memory ($type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }, "repeat": "type" },
  {
   "title": "Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_filesystem_size_bytes{env=\"$environment\", tier=\"db\", type=\"$type\", mountpoint=\"/var/opt/gitlab\"}[$__interval]) - avg_over_time(node_filesystem_free_bytes{env=\"$environment\", tier=\"db\", type=\"$type\", mountpoint=\"/var/opt/gitlab\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory (Total - Free)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval]) - avg_over_time(node_memory_MemFree_bytes{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory (Total - Available)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval]) - avg_over_time(node_memory_MemAvailable_bytes{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMStat Minor Page Faults",
   "type": "timeseries",
   "description": "The number of bytes per second loaded into memory by minor page faults.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgfault{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__rate_interval]) * 4096",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMStat Major Page Faults",
   "type": "timeseries",
   "description": "The number of bytes per second loaded into memory by Major page faults.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__rate_interval]) * 4096",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Table Size (Top 20 Tables)",
   "type": "timeseries",
   "description": "Total storage used for tables with all associated indexes, space maps, toast storage",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, avg_over_time(pg_total_relation_size_bytes{env=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval]) and on (instance) pg_replication_is_replica{env=\"$environment\", tier=\"db\", type=\"$type\"}==0 )\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "{{schemaname}}.{{relname}}",
     "select": [
      [
       { "params": [ "pg_total_relation_size_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Disk Access ($type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }, "repeat": "type" },
  {
   "title": "disk IO wait nvme0n1 (system)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{env=\"$environment\", tier=\"db\", type=\"$type\", device=\"nvme0n1\"}[$__rate_interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} reads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{env=\"$environment\", type=\"$type\", device=~\"nvme0n1\"}[$__rate_interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} writes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "disk IO wait nvme0n2 (DB data)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{env=\"$environment\", type=\"$type\", device=\"nvme0n2\"}[$__rate_interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} reads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{env=\"$environment\", type=\"$type\", device=~\"nvme0n2\"}[$__rate_interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} writes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "disk IO wait nvme0n3 (logging)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{env=\"$environment\", tier=\"db\", type=\"$type\", device=\"nvme0n3\"}[$__rate_interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} reads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{env=\"$environment\", tier=\"db\", type=\"$type\", device=~\"nvme0n3\"}[$__rate_interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} writes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO Utilization nvme0n1 (system)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{env=\"$environment\", tier=\"db\", type=\"$type\", device=~\"nvme0n1\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO Utilization nvme0n2 (DB data)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{env=\"$environment\", tier=\"db\", type=\"$type\", device=~\"nvme0n2\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO Utilization nvme0n3 (logging)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{env=\"$environment\", tier=\"db\", type=\"$type\", device=~\"nvme0n3\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Block Hits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{env=\"$environment\", datname=\"gitlabhq_production\", tier=\"db\", type=\"$type\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} hits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network throughput - transmit and error rate (outbound only) ($type)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "repeat": "type"
  },
  {
   "title": "Overall TCP transmit rate (outbound only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{env=\"$environment\", type=\"$type\"}[$__rate_interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Retransmit rate (outbound only), resending possibly lost packets",
   "type": "timeseries",
   "description": "Typically the Patroni primary db has a *much* higher TCP retransmit rate than the Patroni replica dbs, and the gap is much larger for retransmits than for overall network throughput.  This implies packet loss may occur more often for the Patroni primary db workload and may be a sign that some portion of the current IaaS packet processing pipeline may become saturated during peak workload.  The inferred packet loss may affect some flows/network paths more than others.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{env=\"$environment\", type=\"$type\"}[$__rate_interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "TCP SYN Retransmit Rate",
   "type": "timeseries",
   "description": "TCP SYN retransmits never occur sooner than after 1 second delay, so they always add significant latency to the affected connection attempt.  They could indicate packet loss or downtime for the remote listener endpoint.  Anecdotally, the Patroni nodes overall TCP retransmit rate (inferred packet loss) is usually correlated with workload spikes, but SYN retransmits typically have a stable low flat rate with no bursts.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{env=\"$environment\", type=\"$type\"}[$__rate_interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  { "title": "Checkpoints ($type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 }, "repeat": "type" },
  {
   "title": "Checkpoint Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{environment=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{environment=\"$environment\", tier=\"db\", type=\"$type\"}[$__interval])",
     "legendFormat": "{{fqdn}} sync"
    }
   ]
  },
  {
   "title": "Performed Checkpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_req{environment=\"$environment\", tier=\"db\", type=\"$type\"}[60m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} requested",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_timed{environment=\"$environment\", tier=\"db\", type=\"$type\"}[60m])*60",
     "legendFormat": "{{fqdn}} scheduled"
    }
   ]
  },
  { "title": "Replication Lag Time ($type)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 }, "repeat": "type" },
  {
   "title": "Replication Lag Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "sum(pg_stat_replication_pg_wal_lsn_diff{environment=\"$environment\", tier=\"db\", type=\"$type\"}) by (application_name, slot_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{slot_name}} - {{application_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication Lag Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 124 },
   "targets": [
    {
     "expr": "pg_replication_lag{environment=\"$environment\", tier=\"db\", type=\"$type\"} and pg_replication_is_replica==1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Conflicts",
   "type": "graph",
   "description": "The number of query conflicts occurring on secondaries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 124 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_conflicts{datname=\"gitlabhq_production\", environment=\"$environment\", tier=\"db\", type=\"$type\"}[1m]) * 60",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  { "title": "PGBouncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Query Wait Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "rate(pgbouncer_query_wait_timeout_total{environment=\"$environment\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Connection Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "targets": [
    {
     "expr": "rate(pgbouncer_cant_connect_to_server_total{environment=\"$environment\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}