{
 "title": "PostgreSQL disk IO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "environment", "query": "gprd,gstg" },
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "type",
    "query": {
     "query": "label_values(up{tier=\"db\", type!=\"redis\", environment=\"$environment\"},type)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(up{type=\"$type\", environment=\"$environment\", tier=\"db\"},fqdn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions (all $type hosts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{datname=\"gitlabhq_production\", environment=\"$environment\", tier=\"db\", type=\"$type\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{datname=\"gitlabhq_production\", environment=\"$environment\", tier=\"db\", type=\"$type\"}[1m])",
     "legendFormat": "{{fqdn}} rolled back"
    }
   ]
  },
  {
   "title": "Total IO Wait ($node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{fqdn=\"$node\", device!~\"dm.*\"}[1m])) by (device)",
     "legendFormat": "read {{ device }}"
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])) by (device)",
     "legendFormat": "write {{ device }}"
    }
   ]
  },
  {
   "title": "IO Wait ($node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{fqdn=\"$node\", device!~\"dm.*\"}[1m]) / rate(node_disk_reads_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[1m])",
     "legendFormat": "read {{ device }}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{fqdn=\"$node\", device!~\"dm.*\"}[1m]) / rate(node_disk_writes_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[1m])",
     "legendFormat": "write {{ device }}"
    }
   ]
  },
  {
   "title": "IOPS ($node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(rate(node_disk_writes_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[1m]))",
     "legendFormat": "{{device}} Write IOPS"
    },
    {
     "expr": "(rate(node_disk_reads_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[1m]))",
     "legendFormat": "{{device}} Read IOPS"
    }
   ]
  },
  {
   "title": "Throughput ($node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(node_disk_read_bytes_total{fqdn=\"$node\", device!~\"dm.*\"}[1m]))",
     "legendFormat": "{{ device }} Reads"
    },
    {
     "expr": "(rate(node_disk_written_bytes_total{fqdn=\"$node\", device!~\"dm.*\"}[1m]))",
     "legendFormat": "{{ device }} Writes"
    }
   ]
  },
  {
   "title": "Sum of all Devices Throughput ($node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{fqdn=\"$node\", device!~\"dm.*\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{fqdn=\"$node\", device!~\"dm.*\"}[1m]))",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}