{
 "title": "PostgreSQL Caching",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "environment", "query": "gprd,gstg" },
   {
    "name": "relname",
    "query": "label_values(pg_statio_user_tables_heap_blks_read{environment=\"$environment\"}, relname) "
   }
  ]
 },
 "panels": [
  {
   "title": "Global cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_statio_user_tables_heap_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[1m])) / sum(rate(pg_statio_user_tables_heap_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[1m]) + rate(pg_statio_user_tables_heap_blks_read{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache hit rate per table",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(pg_statio_user_tables_heap_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m])) / sum(rate(pg_statio_user_tables_heap_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m]) + rate(pg_statio_user_tables_heap_blks_read{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m]))",
     "legendFormat": "Heap cache hit ratio"
    },
    {
     "expr": "sum(rate(pg_statio_user_tables_idx_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m])) / sum(rate(pg_statio_user_tables_idx_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m]) + rate(pg_statio_user_tables_idx_blks_read{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m]))",
     "legendFormat": "Index cache hit ratio"
    },
    {
     "expr": "sum(rate(pg_statio_user_tables_toast_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m])) / sum(rate(pg_statio_user_tables_toast_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m]) + rate(pg_statio_user_tables_toast_blks_read{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m]))",
     "legendFormat": "Toast cache hit ratio"
    },
    {
     "expr": "sum(rate(pg_statio_user_tables_tidx_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m])) / sum(rate(pg_statio_user_tables_tidx_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m]) + rate(pg_statio_user_tables_tidx_blks_read{environment=\"$environment\",type=\"patroni\",stage=\"main\",relname=\"$relname\"}[1m]))",
     "legendFormat": "Toast Index cache hit ratio"
    }
   ]
  },
  {
   "title": "Heap: Total cache hit ratio (buffercache) by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(pg_statio_user_tables_heap_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[10m])) by (instance) / sum(rate(pg_statio_user_tables_heap_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[10m]) + rate(pg_statio_user_tables_heap_blks_read{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[10m])) by (instance)"
    }
   ]
  },
  {
   "title": "Index: Total cache hit ratio (buffercache) by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(pg_statio_user_tables_idx_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[1m])) by (instance) / sum(rate(pg_statio_user_tables_idx_blks_hit{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[1m]) + rate(pg_statio_user_tables_idx_blks_read{environment=\"$environment\",type=\"patroni\",stage=\"main\"}[1m])) by (instance)"
    }
   ]
  }
 ]
}