{
 "title": "Postgres IO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(up{tier=\"db\"},environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "query IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=~\"pg.query.*\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}.{{groupname}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=~\"pg.query.*\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}.{{groupname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Write IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=~\"pg.worker.checkpointer\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "wal receiver IO (pg.worker.walwriter)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.worker.walwriter\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.worker.walwriter\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "autovacuum IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.worker.autovacuum\"}[1m])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.autovacuum worker\"}[1m])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "wal sender IO (pg.worker.walsender)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.worker.walsender\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.worker.walsender\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "bgwriter IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.worker.background writer\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.worker.background writer\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "Stat collector IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.stats collector\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.stats collector\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  }
 ]
}