{
 "title": "PostgreSQL Replication Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" }
  ]
 },
 "panels": [
  { "title": "Primary Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Primaries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_replication_is_replica{env=\"$environment\"}==0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary Databases",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "pg_replication_is_replica{env=\"$environment\"}==0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication Slots on Primaries",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "pg_replication_slots_active{env=\"$environment\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Replica Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_replication_is_replica{env=\"$environment\"}==1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replica Databases",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "pg_replication_is_replica{env=\"$environment\"}==1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replica WAL Receiver Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_wal_receiver_status{env=\"$environment\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "pg_replication_is_replica{env=\"$environment\"}==0",
     "legendFormat": "Primary database ({{fqdn}})"
    }
   ]
  },
  { "title": "Replication Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Combined Primary/Replica Slot/Receiver",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_stat_wal_receiver_status{env=\"$environment\"} or on (slot_name,upstream_host) label_replace(pg_replication_slots_active{env=\"$environment\"},\"upstream_host\",\"$1\",\"fqdn\",\"(.*)\") ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Replication Topology",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "<iframe  frameBorder=\"0\" hspace=\"0\" vspace=\"0\" marginheight=\"0\" marginwidth=\"0\" seamless=seamless border=0 width=\"100%\" height=\"500\" src=\"https://prometheus.gitlab.com/consoles/topology.html?environment=$environment\">\n</iframe>\n(Disable Ad-Blocker and/or PrivacyBadger if this doesn't appear)"
   }
  }
 ]
}