local availabilityPromql = import 'gitlab-availability/availability-promql.libsonnet';
local metricsConfig = import 'gitlab-metrics-config.libsonnet';

[
  {
    name: 'Autogenerated Availability Rates',
    interval: '5m',
    rules: availabilityPromql.new(
      metricsConfig.keyServices,
      metricsConfig.aggregationSets.serviceSLIs,
    ).rateRules,
  },
]
