{
 "title": "Canary",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Majority $environment Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, count(omnibus_build_info{environment=~\"$environment\"}) by (version))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Canary Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, count(omnibus_build_info{environment=~\"$environment\", stage=\"cny\"}) by (version))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  { "title": "HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Canary backend status codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code, backend) (\n  backend_code:haproxy_server_http_responses_total:irate1m{backend=\"canary_web\"}\n)",
     "legendFormat": "Backend {{ code }} {{ backend }}"
    }
   ]
  },
  { "title": "Canary Workhorse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Workhorse req/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse-web\", stage=\"cny\", route!=\"^/-/\"}[1m]))",
     "legendFormat": "canary web"
    },
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse-api\",stage=\"cny\", route!=\"^/-/\"}[1m]))",
     "legendFormat": "canary api"
    },
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse-git\",stage=\"cny\", route!=\"^/-/\"}[1m]))",
     "legendFormat": "canary git"
    }
   ]
  },
  {
   "title": "Workhorse req/sec by method and route",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse-web\", stage=\"cny\"}[1m])) by (route,method)",
     "legendFormat": "canary web {{ method }} {{ route }} "
    },
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse-api\",stage=\"cny\"}[1m])) by (route, method)",
     "legendFormat": "canary api  {{ method }} {{ route }} "
    },
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse-git\",stage=\"cny\"}[1m])) by (route)",
     "legendFormat": "canary git {{ route }}"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "p50 latencies for 200s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(status:rails_requests_completed_seconds:p50{ environment=\"$environment\", type=\"web\", status=\"200\", stage=\"cny\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg {{ stage }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max_over_time(status:rails_requests_completed_seconds:p50{ environment=\"$environment\", type=\"web\", status=\"200\", stage=\"cny\"}[5m])",
     "legendFormat": "max {{ stage }}"
    },
    {
     "expr": "avg_over_time(status:rails_requests_completed_seconds:p50{ environment=\"$environment\", type=\"web\", status=\"200\", stage=\"main\"}[5m])",
     "legendFormat": "avg {{ stage }}"
    },
    {
     "expr": "max_over_time(status:rails_requests_completed_seconds:p50{ environment=\"$environment\", type=\"web\", status=\"200\", stage=\"main\"}[5m])",
     "legendFormat": "max {{ stage }}"
    }
   ]
  },
  {
   "title": "p90 latencies for 200s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(status:rails_requests_completed_seconds:p95{ environment=\"$environment\", type=\"web\", status=\"200\", stage=\"cny\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg {{ stage }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max_over_time(status:rails_requests_completed_seconds:p95{ environment=\"$environment\", type=\"web\", status=\"200\", stage=\"cny\"}[5m])",
     "legendFormat": "max {{ stage }}"
    },
    {
     "expr": "avg_over_time(status:rails_requests_completed_seconds:p95{ environment=\"$environment\", type=\"web\", status=\"200\", stage=\"main\"}[5m])",
     "legendFormat": "avg {{ stage }}"
    },
    {
     "expr": "max_over_time(status:rails_requests_completed_seconds:p95{ environment=\"$environment\", type=\"web\", status=\"200\", stage=\"main\"}[$__interval])",
     "legendFormat": "max {{ stage }}"
    }
   ]
  },
  { "title": "Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Exceptions Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(gitlab_transaction_event_rails_exception_total{environment=\"$environment\",  stage=\"cny\"}[$__interval]))",
     "legendFormat": "cny"
    }
   ]
  },
  {
   "title": "Exceptions Rate by Controller",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(gitlab_transaction_event_rails_exception_total{environment=\"$environment\",stage=\"cny\"}[$__interval])) by (controller)",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  { "title": "VM stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "web canary cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "repeat": "type",
   "targets": [
    {
     "expr": "avg(avg_over_time(instance:node_cpu_in_use:ratio{environment=\"$environment\", type=\"web\", stage!=\"cny\"}[$__interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "max(max_over_time(instance:node_cpu_in_use:ratio{environment=\"$environment\", type=\"web\", stage!=\"cny\"}[$__interval]))",
     "legendFormat": "max"
    },
    {
     "expr": "min(min_over_time(instance:node_cpu_in_use:ratio{environment=\"$environment\", type=\"web\", stage!=\"cny\"}[$__interval]))",
     "legendFormat": "min"
    },
    {
     "expr": "avg_over_time(instance:node_cpu_in_use:ratio{environment=\"$environment\", type=\"web\", stage=\"cny\"}[$__interval])",
     "legendFormat": "avg-cny"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "node_memory_MemTotal{fqdn=\"$node\"} - node_memory_MemFree{fqdn=\"$node\"} - node_memory_Buffers{fqdn=\"$node\"} - node_memory_Cached{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_SwapTotal{fqdn=\"$node\"} - node_memory_SwapFree{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Swap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_MemTotal{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_SwapTotal{fqdn=\"$node\"}",
     "legendFormat": "Swap Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node\"} - node_memory_MemFree_bytes{fqdn=\"$node\"} - node_memory_Buffers_bytes{fqdn=\"$node\"} - node_memory_Cached_bytes{fqdn=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node\"} - node_memory_SwapFree_bytes{fqdn=\"$node\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node\"}",
     "legendFormat": "Swap Total"
    }
   ]
  }
 ]
}