{
 "title": "Fleet Overview",
 "tags": [
  "prometheus",
  "drilldown",
  "triage",
  "unmanaged"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(up{environment!=\"\"}, environment)"
   },
   {
    "name": "stage",
    "query": "label_values(up{environment=\"$environment\"}, stage)"
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GitLab.com",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"gitlab.com\", job=\"blackbox-ssl\"}==bool 200",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "UP",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pages",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(probe_http_status_code{instance=\"https://gitlab-examples.gitlab.io\",job=\"blackbox\"}) ==bool 200",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "UP",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Registry",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(probe_success{instance=\"registry.gitlab.com\", job=\"blackbox-ssl\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "UP",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Staging",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(probe_success{instance=~\"^https://staging.*\", job=\"blackbox\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "UP",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "ELK",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(up{job=\"elk-elasticsearch\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "UP",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ALERTS{severity=\"critical\", alertstate=\"firing\"}) OR vector(0)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "UP",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Healthy targets",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(up{environment=\"$environment\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "UP",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {}
     ]
    },
    {
     "title": "Chef Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(chef_client_error{environment=\"$environment\"} != 0) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "WEB HTTP Status Codes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(backend_code:haproxy_server_http_responses_total:irate1m{tier=\"lb\", environment=\"$environment\", backend=\"web\", code!=\"other\"}) by (code)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API HTTP Status Codes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(backend_code:haproxy_server_http_responses_total:irate1m{tier=\"lb\", environment=\"$environment\", backend=\"api\", code!=\"other\"}) by (code)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git over HTTPS Status Codes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(backend_code:haproxy_server_http_responses_total:irate1m{tier=\"lb\", environment=\"$environment\", backend=\"https_git\", code!=\"other\"}) by (code)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LBs CPU Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "job:node_cpu_utilization:avg_ratio{environment=\"gprd\", stage=\"main\", tier=\"lb\", type=\"frontend\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  { "title": "Worker CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Web CPU Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "job:node_cpu_utilization:avg_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"web\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "job:node_cpu_utilization:max_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"web\"}",
     "legendFormat": "max"
    },
    {
     "expr": "job:node_cpu_utilization:min_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"web\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "API CPU Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "job:node_cpu_utilization:avg_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"api\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "job:node_cpu_utilization:max_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"api\"}",
     "legendFormat": "max"
    },
    {
     "expr": "job:node_cpu_utilization:min_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"api\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Git CPU Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "job:node_cpu_utilization:avg_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"git\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Average",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "job:node_cpu_utilization:max_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"git\"}",
     "legendFormat": "max"
    },
    {
     "expr": "job:node_cpu_utilization:min_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"git\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "AVG Sidekiq CPU Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "job:node_cpu_utilization:avg_ratio{environment=\"$environment\", stage=\"$stage\", tier=\"sv\", type=\"sidekiq\"}",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  { "title": "Worker Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Web Workers Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{tier=\"sv\", environment=\"$environment\", stage=\"$stage\", type=\"web\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "API Workers Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{tier=\"sv\", environment=\"$environment\", stage=\"$stage\", type=\"api\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Workers Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{tier=\"sv\", environment=\"$environment\", stage=\"$stage\", type=\"git\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "AVG Sidekiq Workers Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{tier=\"sv\", environment=\"$environment\", stage=\"$stage\", type=\"sidekiq\"})\nby (priority)",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  { "title": "Git NFS Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Git CPU Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "job:node_cpu_utilization:avg_ratio{environment=\"gprd\", stage=\"main\", tier=\"stor\", type=\"gitaly\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{shard}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git NFS Servers Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{environment=\"$environment\", tier=\"stor\", type=\"gitaly\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Git NFS Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{environment=\"$environment\", tier=\"stor\", type=\"gitaly\", device!=\"tmpfs\"} \n  - \nnode_filesystem_avail_bytes{environment=\"$environment\", tier=\"stor\", type=\"gitaly\", device!=\"tmpfs\"}",
     "legendFormat": "Used - {{fqdn}} {{ device }}"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{environment=\"$environment\", tier=\"stor\", type=\"gitaly\"}) by (device)",
     "legendFormat": "Total {{device}}"
    }
   ]
  },
  {
   "title": "Aggregate Git NFS Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", environment=\"$environment\", tier=\"stor\", type=\"gitaly\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", environment=\"$environment\", tier=\"stor\", type=\"gitaly\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Outbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Git & Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Git Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_backend_current_sessions{tier=\"lb\", environment=\"$environment\", backend=\"ssh\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ssh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{tier=\"lb\", environment=\"$environment\", backend=\"https_git\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "https",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Builds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ci_runner_builds{state=\"running\"}) by (job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{job}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq Running Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs_count{tier=\"db\", environment=\"$environment\", type=\"redis\", name!~\"(ActiveJob|Devise).*\"} and on (fqdn) gitlab:redis_master)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Jobs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Database Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "node_load1{tier=\"db\", environment=\"$environment\", type=\"patroni\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate DB IO Wait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{tier=\"db\", environment=\"$environment\", type=\"patroni\", device=~\"sd.*\"}[$__interval])) by (instance)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "max(pg_stat_replication_pg_xlog_location_diff{tier=\"db\", environment=\"$environment\", type=\"patroni\"}) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Network Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Aggregate Web Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", tier=\"sv\", environment=\"$environment\", type=\"web\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "incoming",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", tier=\"sv\", environment=\"$environment\", type=\"web\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "outgoing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate API Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", tier=\"sv\", environment=\"$environment\", type=\"api\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "incoming",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", tier=\"sv\", environment=\"$environment\", type=\"api\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "outgoing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate Git Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", tier=\"sv\", environment=\"$environment\", type=\"git\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "incoming",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!=\"lo\", tier=\"sv\", environment=\"$environment\", type=\"git\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "outgoing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate Sidekiq Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", tier=\"sv\", environment=\"$environment\", type=\"sidekiq\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", tier=\"sv\", environment=\"$environment\", type=\"sidekiq\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Outbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Workhorse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Git Fetch HTTP Reqs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(gitlab_workhorse_git_http_requests{service=\"git-upload-pack\", code=\"200\"}[$__interval])) by (method)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{method}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Fetch HTTP Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(gitlab_workhorse_git_http_bytes{service=\"git-upload-pack\", code=\"200\"}[1m])) by (method)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{method}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Push HTTP Reqs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(gitlab_workhorse_git_http_requests{service=\"git-receive-pack\", code=\"200\"}[1m])) by (method)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{method}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Push HTTP Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(gitlab_workhorse_git_http_bytes{service=\"git-receive-pack\", code=\"200\"}[1m])) by (method)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{method}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Unicorns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Unicorn Kill Timeout per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(unicorn_pid_timeouts_total{environment=\"$environment\"}[$__interval])) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Unicorn Process Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "avg(process_age_seconds{environment=\"$environment\", name=\"unicorn\", quantile=\"99th\", type!=\"sidekiq\"}) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} p90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Unicorn Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "avg(process_memory_bytes{environment=\"$environment\", name=\"unicorn\",field=\"VmRSS\", quantile=\"99th\", type!=\"sidekiq\"}) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} p90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Avg Sidekiq Process Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "avg(process_age_seconds{name=\"sidekiq\", quantile=\"99th\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "min(process_age_seconds{name=\"sidekiq\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Avg Sidekiq Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "avg(process_memory_bytes{name=\"sidekiq\",field=\"VmRSS\", quantile=\"99th\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(process_memory_bytes{name=\"sidekiq\",field=\"VmRSS\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "LBs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "GitLab Front-end LBs Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", environment=\"$environment\", fqdn=~\"fe.*\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} inbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", environment=\"$environment\", fqdn=~\"fe.*\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} outbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GitLab Pages LBs Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", environment=\"$environment\", fqdn=~\"pages.*\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} inbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", environment=\"$environment\",  fqdn=~\"pages.*\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} outbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GitLab AltSSH LBs Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", environment=\"$environment\", fqdn=~\"altssh.*\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} inbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", environment=\"$environment\", fqdn=~\"altssh.*\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} outbound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Git Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Git SSH Upload Pack Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "process_age_seconds{name=\"git_upload_pack_ssh\", quantile=\"99th\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ssh p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git HTTP Upload Pack Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "process_age_seconds{name=\"git_upload_pack_http\", quantile=\"99th\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git SSH Upload Pack Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "process_memory_bytes{name=\"git_upload_pack_ssh\",field=\"VmRSS\", quantile=\"99th\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workhorse HTTP git sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sum(increase(gitlab_workhorse_git_http_sessions_active[1m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git HTTP Upload Pack Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "process_memory_bytes{name=\"git_upload_pack_http\",field=\"VmRSS\", quantile=\"99th\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workers Git Processes Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum(process_count{name=~\"git.*\"}) by (name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}