{
 "title": "Fleet Utilization",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=~\"prometheus.*\"}, env)"
   },
   {
    "name": "type",
    "query": "label_values(up{env=~\"$env\",job=~\"node(-exporter)?\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization - $env",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "env",
   "targets": [
    {
     "expr": "avg by (environment, type) (quantile_over_time(0.95, instance:cpu_utilization:ratio_avg{env=~\"$env\",type=~\"$type\"}[$__interval]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg by (environment) (quantile_over_time(0.95, instance:cpu_utilization:ratio_avg{environment=~\"$env\",type=~\"$type\"}[$__interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Memory Utilization - $env",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "repeat": "env",
   "targets": [
    {
     "expr": "avg by (environment, type) (quantile_over_time(0.95, instance:memory_utilization:ratio_avg{env=~\"$env\",type=~\"$type\"}[$__interval]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg by (environment) (quantile_over_time(0.95, instance:memory_utilization:ratio_avg{environment=~\"$env\",type=~\"$type\"}[$__interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Worst 10 CPU Utilization $env",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "repeat": "env",
   "targets": [
    {
     "expr": "bottomk(10, avg by (fqdn, environment) (quantile_over_time(0.95, instance:cpu_utilization:ratio_q95{env=~\"$env\",type=~\"$type\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Worst 10 Memory Utilization $env",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "repeat": "env",
   "targets": [
    {
     "expr": "bottomk(10, avg by (fqdn, environment) (quantile_over_time(0.95, instance:memory_utilization:ratio_q95{env=~\"$env\",type=~\"$type\"}[$__range])))"
    }
   ]
  }
 ]
}