{
 "title": "General Triage: Components",
 "description": "$type",
 "tags": [
  "general triage",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_ds", "query": "prometheus" },
   { "name": "environment", "query": "label_values(up, environment)" },
   {
    "name": "type",
    "query": "label_values(up{environment=\"$environment\"}, type)"
   },
   { "name": "sigma", "label": "σ", "query": "0.5,1,1.5,2,2.5,3" },
   {
    "name": "component_availability",
    "query": "label_values(gitlab_component_availability:ratio{environment=\"$environment\", type=\"$type\"}, component)"
   },
   {
    "name": "component_ops",
    "query": "label_values(gitlab_component_ops:rate{environment=\"$environment\", type=\"$type\"}, component)"
   },
   {
    "name": "component_apdex",
    "query": "label_values(gitlab_component_apdex:ratio{environment=\"$environment\", type=\"$type\"}, component)"
   },
   {
    "name": "component_errors",
    "query": "label_values(gitlab_component_errors:rate{environment=\"$environment\", type=\"$type\"}, component)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"} > 0) without (monitor)"
    },
    {
     "expr": "sum(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"pending\"} > 0) without (monitor)"
    }
   ]
  },
  { "title": "Per-Component Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "\"$component_availability\" Service Component Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "repeat": "component_availability",
   "targets": [
    {
     "expr": "gitlab_component_availability:ratio{environment=\"$environment\", type=\"$type\", component=\"$component_availability\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ component }} ({{ monitor }})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Per-Component Operation Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$component_ops Service Operation Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "repeat": "component_ops",
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_component_ops:rate{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}[$__interval])) by (component)",
     "legendFormat": "{{ component }} component"
    },
    {
     "expr": "sum(\ngitlab_component_ops:rate:avg_over_time_1w{service=\"\", environment=\"$environment\", type=\"$type\", component=\"$component_ops\"} + \n$sigma * gitlab_component_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}\n)",
     "legendFormat": "upper"
    },
    {
     "expr": "sum(\nclamp_min(gitlab_component_ops:rate:avg_over_time_1w{service=\"\", environment=\"$environment\", type=\"$type\", component=\"$component_ops\"} \n- $sigma * gitlab_component_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}, 0)\n)",
     "legendFormat": "lower"
    }
   ]
  },
  { "title": "Per-Component Apdex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$component_apdex Component Apdex",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "repeat": "component_apdex",
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"}[$__interval])",
     "legendFormat": "{{ component }} component ({{ monitor }})"
    },
    {
     "expr": "clamp_min(gitlab_component_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"} - $sigma * gitlab_component_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"}, 0)",
     "legendFormat": "lower"
    },
    {
     "expr": "clamp_max(gitlab_component_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"} + $sigma * gitlab_component_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"}, 1)",
     "legendFormat": "upper"
    }
   ]
  },
  { "title": "Per-Component Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$component_errors Component - Error Rates per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "repeat": "component_errors",
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_errors:rate{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"}[$__interval]) * 60",
     "legendFormat": "{{ component }} component"
    },
    {
     "expr": "(gitlab_component_errors:rate:avg_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"} + $sigma * gitlab_component_errors:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"}) * 60",
     "legendFormat": "upper"
    },
    {
     "expr": "clamp_min((gitlab_component_errors:rate:avg_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"} - $sigma * gitlab_component_errors:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"}) * 60, 0)",
     "legendFormat": "lower"
    }
   ]
  },
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{type=\"$type\", environment=\"$environment\", mode=\"idle\"}[$__interval])) by (fqdn)",
     "legendFormat": "{{ fqdn }} "
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "avg(\n(node_memory_MemTotal_bytes{type=\"$type\", environment=\"$environment\"} - \n(\n  node_memory_MemFree_bytes{type=\"$type\", environment=\"$environment\"} + \n  node_memory_Buffers_bytes{type=\"$type\", environment=\"$environment\"} + \n  node_memory_Cached_bytes{type=\"$type\", environment=\"$environment\"}\n) \n)\n\n/ node_memory_MemTotal_bytes{type=\"$type\", environment=\"$environment\"}\n) by (fqdn)",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  }
 ]
}