{
 "title": "kubernetes: USE Method /  Multi-Cluster",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/354678442 at Tue Nov 19 09:39:53 UTC 2019",
 "tags": [
  "kubernetes",
  "kubernetes",
  "infrastucture",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node:node_cpu_utilisation:avg1m * node:node_num_cpu:sum) by (cluster) / sum(node:node_num_cpu:sum) by (cluster)",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node:node_cpu_saturation_load1:) by (cluster) / sum(min(kube_pod_info) by (node, cluster)) by(cluster)",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node:cluster_memory_utilisation:ratio) by (cluster)",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(node:node_memory_swap_io_bytes:sum_rate) by (cluster)",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node:node_disk_utilisation:avg_irate) by (cluster) / sum(:kube_pod_info_node_count:) by (cluster)",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node:node_disk_saturation:avg_irate) by (cluster) / sum(:kube_pod_info_node_count:) by (cluster) ",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(node:node_net_utilisation:sum_irate) by (cluster)",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(node:node_net_saturation:sum_irate) by (cluster)",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"} - node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (cluster)\n/ sum(node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (cluster)\n",
     "legendFormat": "{{cluster}}",
     "legendLink": "/d/d595159af7dd483158f9e10688363744/k8s-cluster-rsrc-use"
    }
   ]
  }
 ]
}