{
 "title": "Leaderboard",
 "tags": [
  "leaderboard",
  "pages",
  "unmanaged"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "label": "path", "query": "$namespace.*" },
   { "name": "testname", "query": "$namespace.$path.*" },
   {
    "name": "domains",
    "label": "domains",
    "query": "$namespace.$path.$testname.pageSummary.*"
   },
   {
    "name": "pages",
    "label": "pages",
    "query": "$namespace.$path.$testname.pageSummary.$domains.*"
   },
   {
    "name": "browser",
    "label": "browser",
    "query": "$namespace.$path.$testname.pageSummary.$domains.$pages.*"
   },
   { "name": "function", "query": "min,mean,median,p90,max" },
   {
    "name": "connectivity",
    "query": "$namespace.$path.$testname.pageSummary.$domains.$pages.$browser.*"
   }
  ]
 },
 "panels": [
  { "title": "Visual Metrics  [$function]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "First Visual Change",
   "type": "bargauge",
   "description": "The first visual change is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 'average'),4, 5)"
    }
   ]
  },
  {
   "title": "Largest image",
   "type": "bargauge",
   "description": "The largest image is the time when the largest image within the viewport is painted and on its final position. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "bargauge",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "Visual Readiness",
   "type": "bargauge",
   "description": "Visual readiness is the time between the first visual change and the last visual change within the viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualReadiness.$function,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "History Visual Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Visual Change",
     "type": "graph",
     "description": "The first visual change is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 4, 5)"
      }
     ]
    },
    {
     "title": "Largest image",
     "type": "graph",
     "description": "The largest image is the time when the largest image within the viewport is painted and on its final position. It is calculated by analyzing a video recording of the screen.",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function, 4, 5)"
      }
     ]
    },
    {
     "title": "SpeedIndex",
     "type": "graph",
     "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, 4, 5)"
      }
     ]
    },
    {
     "title": "Visual Readiness",
     "type": "graph",
     "description": "Visual readiness is the time between the first visual change and the last visual change within the viewport. It is calculated by analyzing a video recording of the screen.",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.visualMetrics.VisualReadiness.$function, 4, 5)"
      }
     ]
    }
   ]
  },
  { "title": "CPU  [$function]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU time spent script evaluation",
   "type": "bargauge",
   "description": "CPU time spent evaluating JavaScript. Calculated using [Tracium](https://github.com/aslushnikov/tracium). This is a Chrome only metric at the moment.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.categories.scriptEvaluation.$function,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "CPU time spent render",
   "type": "bargauge",
   "description": "CPU time spent rendering the page. Calculated using [Tracium](https://github.com/aslushnikov/tracium). This is a Chrome only metric at the moment.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.categories.paintCompositeRender.$function,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "Carbon emission (enable with --sustainability.enable)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated carbon emission per page view",
     "type": "bargauge",
     "description": "The estimated carbon emission is calculated using the sustainable web plugin, developed together with the Green Web Foundation.",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.sustainable.co2PerPageView.$function, 'average'),4, 5)"
      }
     ]
    }
   ]
  },
  { "title": "Technical metrics  [$function]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Load Event End",
   "type": "bargauge",
   "description": "Load Event End is when the load event end event fires in the Navigation Timing API",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.loadEventEnd.$function,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "Fully Loaded",
   "type": "bargauge",
   "description": "Fully loaded time when the last of all assets is downloaded on the page.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "Technical metrics history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Event End",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.loadEventEnd.$function, 4, 5)"
      }
     ]
    },
    {
     "title": "Fully Loaded",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, 4, 5)"
      }
     ]
    }
   ]
  },
  { "title": "JavaScript  [$function]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "JavaScript Transfer Size",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.contentTypes.javascript.transferSize,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "JavaScript Content Size",
   "type": "bargauge",
   "description": "The JavaScript size unpacked.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.contentTypes.javascript.contentSize,'average'), 4, 5)"
    }
   ]
  },
  { "title": "Requests and size ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Total number or requests",
   "type": "stat",
   "description": "Total number of requests for the full page.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.requests), 4, 5)"
    }
   ]
  },
  {
   "title": "Total page transfer size (over the wire)",
   "type": "stat",
   "description": "Total page weight (compressed over the wire).",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortByMaxima($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.transferSize), 4, 5)"
    }
   ]
  },
  { "title": "Requests and size bars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Total number of requests",
   "type": "bargauge",
   "description": "Total number of requests for the full page.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.requests,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "Total page transfer size (over the wire)",
   "type": "bargauge",
   "description": "Total page weight (compressed over the wire).",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.transferSize,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "Requests and size history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.requests, 4, 5)"
      }
     ]
    },
    {
     "title": "Total transfer size",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.pagexray.transferSize, 4, 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Axe violations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Axe critical violations",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.axe.violations.critical.$function, 'average'),4, 5)"
      }
     ]
    },
    {
     "title": "Axe serious violations",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.axe.violations.serious.$function, 'average'),4, 5)"
      }
     ]
    }
   ]
  },
  { "title": "CPU Long Task  [$function]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Number of CPU Long Tasks (average)",
   "type": "bargauge",
   "description": "The average number of CPU Long Tasks per page. A CPU long Task is by default a CPU task that takes longer than 50 ms to run. This metrics is Chrome only at the moment.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.$function,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "Longest long task",
   "type": "bargauge",
   "description": "This is the longest CPU task for each page (if they are over 50 ms long). This metrics is Chrome only at the moment.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.max,'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "CPU Long Task history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "collapsed": true,
   "panels": [
    {
     "title": "Longest CPU Long Tasks",
     "type": "graph",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 73 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.max, 3, 4)"
      }
     ]
    },
    {
     "title": "Number of CPU Long Tasks",
     "type": "graph",
     "gridPos": { "h": 15, "w": 8, "x": 8, "y": 73 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.$function, 3, 4)"
      }
     ]
    },
    {
     "title": "Number of CPU Long Tasks before First Paint",
     "type": "graph",
     "gridPos": { "h": 15, "w": 8, "x": 16, "y": 73 },
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeFirstPaint.tasks.median, 3, 4)"
      }
     ]
    }
   ]
  },
  { "title": "Third parties  [$function]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Third party request",
   "type": "bargauge",
   "description": "Third party requests are calculated using the [Third party web](https://github.com/patrickhulce/third-party-web) library.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.thirdparty.requests.total.$function, 'average'), 4, 5)"
    }
   ]
  },
  {
   "title": "% third party request",
   "type": "bargauge",
   "description": "Third party % are calculated using the [Third party web](https://github.com/patrickhulce/third-party-web) library.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.thirdparty.requests.percentage.$function, 'average'), 4, 5)"
    }
   ]
  },
  { "title": "Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Performance score",
   "type": "bargauge",
   "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.coach.advice.performance.score, 'average', true),4, 5)"
    }
   ]
  },
  {
   "title": "Privacy score",
   "type": "bargauge",
   "description": "The privacy score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using user privacy best practices.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.coach.advice.privacy.score, 'average', true),4, 5)"
    }
   ]
  }
 ]
}