{
 "title": "Node - iostat",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=\"node\",monitor!=\"runners\"}, instance)"
   },
   {
    "name": "device",
    "query": "label_values(node_disk_read_bytes_total{instance=\"$instance\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "IO In Flight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IO In Flight $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "device",
   "targets": [
    {
     "expr": "avg_over_time(node_disk_io_now{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "Avg"
    },
    {
     "expr": "max_over_time(node_disk_io_now{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "iostat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Reads Merged (rrqm/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_merged_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Writes Merged (wrqm/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_merged_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Reads Completed (r/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Writes Completed (w/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read Bytes (rkB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Write Bytes (wkB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Average Read Size Bytes (avgrq-sz)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\",device=~\"$device\"}[$__interval])\n/\nrate(node_disk_reads_completed_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Average Write Size Bytes (avgqu-sz)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\",device=~\"$device\"}[$__interval])\n/\nrate(node_disk_writes_completed_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read Latency (r_await)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"$instance\",device=~\"$device\"}[$__interval])\n/ rate(node_disk_reads_completed_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Write Latency (w_await)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"$instance\",device=~\"$device\"}[$__interval])\n/ rate(node_disk_writes_completed_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Queue Length (avgqu-sz)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Utilization (%util)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\",device=~\"$device\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}