{
 "title": "Sitespeed - Plus1",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "query": "$base.*" },
   { "name": "testtype", "query": "$base.$path.*" },
   {
    "name": "group",
    "label": "domain",
    "query": "$base.$path.$testtype.pageSummary.*"
   },
   {
    "name": "page",
    "query": "$base.$path.$testtype.pageSummary.$group.*"
   },
   { "name": "type", "label": "GPSI type", "query": "mobile,desktop" }
  ]
 },
 "panels": [
  { "title": "Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Use the +1 container to get metrics from Lighthouse and GPSI"
   }
  },
  {
   "title": "GPSI Score",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.score.*, 9)"
    }
   ]
  },
  {
   "title": "GPSI Score",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.score.*, 9)"
    }
   ]
  },
  {
   "title": "CrUX Chrome data for origin $group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_CONTENTFUL_PAINT_MS.percentile, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.LARGEST_CONTENTFUL_PAINT_MS.percentile, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_INPUT_DELAY_MS.percentile, 'First Input Delay')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.percentile, 'Cumulative Layout Shift')"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.LARGEST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.LARGEST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.LARGEST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_INPUT_DELAY_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_INPUT_DELAY_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_INPUT_DELAY_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.LARGEST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.LARGEST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.LARGEST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_INPUT_DELAY_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_INPUT_DELAY_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.FIRST_INPUT_DELAY_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.summary.$group.gpsi.$type.originLoadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "CrUX Chrome data for page $group$page",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "First Contentful Paint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 10)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.LARGEST_CONTENTFUL_PAINT_MS.fast, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.LARGEST_CONTENTFUL_PAINT_MS.moderate, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.LARGEST_CONTENTFUL_PAINT_MS.slow, 100), 10)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.fast, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.moderate, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.slow, 100), 10)"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE, 100), 10)"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 10)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.LARGEST_CONTENTFUL_PAINT_MS.fast, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.LARGEST_CONTENTFUL_PAINT_MS.moderate, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.LARGEST_CONTENTFUL_PAINT_MS.slow, 100), 10)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 48 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.fast, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.moderate, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.slow, 100), 10)"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 48 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 100), 10)"
    },
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 100), 10)"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Loading experience percentile",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.percentile, 'First Contentful Paint')"
    },
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.percentile, 'First Input Delay')"
    },
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.LARGEST_CONTENTFUL_PAINT_MS.percentile, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "title": "Loading experience percentile",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.gpsi.$type.loadingExperience.CUMULATIVE_LAYOUT_SHIFT_SCORE.percentile, 'Cumulative Layout Shift')"
    }
   ]
  },
  { "title": "Lighthouse Google Web Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.lighthouse.audits.first-contentful-paint.numericValue, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.lighthouse.audits.largest-contentful-paint.numericValue, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.lighthouse.audits.total-blocking-time.numericValue, 'Total Blocking ime')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.lighthouse.audits.cumulative-layout-shift.numericValue, 'Cumulative Layout Shift')"
    }
   ]
  },
  { "title": "Lighthouse score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Lighthouse Score",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.$testtype.pageSummary.$group.$page.lighthouse.categories.*.score, 100), 8)"
    }
   ]
  },
  {
   "title": "Lighthouse Google Web Vitals history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 }
  },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.lighthouse.audits.first-contentful-paint.numericValue, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.lighthouse.audits.largest-contentful-paint.numericValue, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.lighthouse.audits.total-blocking-time.numericValue, 'Total Blocking Time')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias($base.$path.$testtype.pageSummary.$group.$page.lighthouse.audits.cumulative-layout-shift.numericValue, 'Cumulative Layout Shift')"
    }
   ]
  }
 ]
}