{
 "title": "Sitespeed - LCP Leaderboard",
 "tags": [
  "leaderboard",
  "pages",
  "unmanaged"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "label": "path", "query": "$namespace.*" },
   { "name": "testname", "query": "$namespace.$path.*" },
   {
    "name": "domains",
    "label": "domains",
    "query": "$namespace.$path.$testname.pageSummary.*"
   },
   {
    "name": "pages",
    "label": "pages",
    "query": "$namespace.$path.$testname.pageSummary.$domains.*"
   },
   {
    "name": "browser",
    "label": "browser",
    "query": "$namespace.$path.$testname.pageSummary.$domains.$pages.*"
   },
   { "name": "function", "query": "min,mean,median,p90,max" },
   {
    "name": "connectivity",
    "query": "$namespace.$path.$testname.pageSummary.$domains.$pages.$browser.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Routes with good LCP (<2.5s)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "asPercent(countSeries(currentBelow($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 2500)), countSeries($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function))"
    }
   ]
  },
  {
   "title": "Measured Routes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "countSeries($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function)"
    }
   ]
  },
  {
   "title": "Average LCP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "averageSeries($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function)"
    }
   ]
  },
  {
   "title": "LCP Leaderboard",
   "type": "bargauge",
   "description": "LCP of all monitored routes",
   "gridPos": { "h": 44, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function),  5)"
    }
   ]
  },
  {
   "title": "LCP History",
   "type": "graph",
   "description": "LCP History of all monitored routes",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function),  5)"
    }
   ]
  },
  {
   "title": "LCP Numbers",
   "type": "table",
   "description": "LCP History of all monitored routes",
   "gridPos": { "h": 44, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function),  5)"
    }
   ]
  },
  {
   "title": "Time to First Byte (BE Duration)",
   "type": "bargauge",
   "gridPos": { "h": 41, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.$testname.pageSummary.$domains.$pages.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function),  5)"
    }
   ]
  }
 ]
}