{
 "title": "Storage Stats",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"prometheus\"}, env)"
   },
   {
    "name": "environment",
    "query": "label_values(node_filesystem_avail_bytes{device=\"/dev/sdb\"}, environment)"
   },
   {
    "name": "node",
    "query": "label_values(node_filesystem_avail_bytes{environment=\"$env\",device=\"/dev/sdb\"}, fqdn)"
   }
  ]
 },
 "panels": [
  { "title": "Used Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - instance:node_filesystem_avail:ratio{fqdn=~\"$node-stor-$env.c.gitlab-.*.internal\",device=\"/dev/sdb\", environment=\"$env\",monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Storage Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Git Storage Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_filesystem_size_bytes{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\", monitor=\"default\"}\n    -\n  node_filesystem_avail_bytes{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\", monitor=\"default\"}\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(node_filesystem_size_bytes{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages Storage Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_filesystem_size_bytes{instance=~\"pages-01.*\",  device=\"/dev/sdb\", monitor=\"default\"}\n    -\n  node_filesystem_avail_bytes{instance=~\"pages-01.*\",  device=\"/dev/sdb\", monitor=\"default\"}\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"pages-01.*\", device=\"/dev/sdb\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Share Storage Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_filesystem_size_bytes{instance=~\"share-01.*\", device=\"/dev/sdb\"}\n    -\n  node_filesystem_avail_bytes{instance=~\"share-01.*\", device=\"/dev/sdb\"}\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"share-01.*\", device=\"/dev/sdb\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Git Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Git IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.+\", monitor=\"default\"}[$__interval])) without (device)\n  /\ncount(node_disk_io_time_seconds_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.+\", monitor=\"default\"}) without (device)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git NFS CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_in_use:ratio{environment=\"$env\", tier=\"stor\", type=\"gitaly\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git NFS Host Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_load1{environment=\"$env\", tier=\"stor\", type=\"gitaly\", monitor=\"default\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Shared Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Shared NFS IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{environment=\"$env\", tier=\"stor\", type=\"\",device=~\"sd.+\"}[$__interval])) without (device)\n  /\ncount(node_disk_io_time_seconds_total{environment=\"$env\", tier=\"stor\", type=\"\",device=~\"sd.+\"}) without (device)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared NFS Host Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{environment=\"$env\", tier=\"stor\", type=\"\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared NFS CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_in_use:ratio{environment=\"$env\", tier=\"stor\", type=\"\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Git IO Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Git NFS Fleet READ IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "avg(rate(node_disk_reads_completed_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.*\", monitor=\"default\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(rate(node_disk_reads_completed_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.*\"}[$__interval]))",
     "legendFormat": "max"
    },
    {
     "expr": "min(rate(node_disk_reads_completed_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.*\", monitor=\"default\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Git NFS Fleet Combined IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "avg(rate(node_disk_writes_completed_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.*\", monitor=\"default\"}[$__interval])) by (fqdn)\n+ \navg(rate(node_disk_reads_completed_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.*\", monitor=\"default\"}[$__interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }} ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NFS Total IO Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(node_disk_io_time_seconds_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device!=\"dm.*\"}[1m])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Shared NFS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Shared NFS Fleet READ IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{environment=\"$env\", tier=\"stor\", type=\"\", device!=\"dm.*\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}} reads"
    }
   ]
  },
  {
   "title": "Shared NFS Fleet WRITE IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{environment=\"$env\", tier=\"stor\", type=\"\", device!=\"dm.*\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}} writes"
    }
   ]
  },
  {
   "title": "Git NFS Storage usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\", monitor=\"default\"} - node_filesystem_free_bytes{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\", monitor=\"default\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git NFS Fleet Combined IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "avg(rate(node_disk_writes_completed_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.*\", monitor=\"default\"}[$__interval])) by (fqdn)\n+ \navg(rate(node_disk_reads_completed_total{environment=\"$env\", tier=\"stor\", type=\"gitaly\", device=~\"sd.*\", monitor=\"default\"}[$__interval])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }} ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}